# docker build -t webis/tira-application:basis-0.0.94 -f Dockerfile.application-dev .
FROM ubuntu:22.04

RUN apt-get update \
	&& apt-get upgrade -y \
	&& apt-get install -y python3 python3-pip python-is-python3 mysql-client nginx sudo podman git \
	&& apt-get install -y gcc default-libmysqlclient-dev pkg-config \
	&& rm -Rf /var/cache/apt \
	&& rm -Rf /root/.cache/pip \
	&& echo '%podman ALL=(ALL) ALL' > /etc/sudoers.d/podman

ADD requirements.txt /requirements.txt

RUN pip3 install -r /requirements.txt \
	&& rm -Rf /var/cache/apt \
	&& rm -Rf /root/.cache/pip

RUN pip3 uninstall -y diffir \
	&& pip3 install git+https://github.com/mam10eks/diffir && \
	addgroup --gid 1010 tira && \
	adduser --disabled-password --uid 1010 --ingroup tira tira && \
	adduser tira root && \
	mkdir /tira-tmp-debug && \
	mkdir -p /tira/application/src/tira && \
	mkdir -p /etc/nginx/logs && \
	mkdir -p /mnt/ceph/tira && \
	mkdir -p /root/.ir_datasets \
	&& rm -Rf /var/cache/apt \
	&& rm -Rf /root/.cache/pip \
	&& apt-get install -y fuse-overlayfs

COPY src/tira_nginx.conf /etc/nginx/nginx.conf

RUN chown -R tira:tira /usr/local && \
	chmod 777 /var/run/ && \
	echo "tira ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers &&\
	touch /var/log/tira_debug.txt &&\
	touch /tira/application/src/debug.log &&\
	chown tira:tira /var/log/tira_debug.txt &&\
	chown tira:tira /tira/application/src/debug.log &&\
	chown -R tira:tira /root/.ir_datasets &&\
	chmod 777 /root/.ir_datasets &&\
	chmod 777 /root &&\
	mkdir -p /home/tira/.tira &&\
	mkdir -p /mnt/ceph/tira/log/tira-application &&\
	mkdir /home/tira/.ssh &&\
	mkdir /mnt/ceph/tira/state &&\
	mkdir -p /usr/share/nginx/logs/ && \
	chmod 777 /usr/share/nginx/logs/ && \
	touch /mnt/ceph/tira/state/tira_vm_states.sqlite3 &&\
	chown tira:tira -R /home/tira &&\
	chown tira:tira -R /tira

RUN pip3 install tira==0.0.97 ir-measures==0.3.1

