FROM node:lts

COPY src/tira/frontend-vuetify /src/tira/frontend-vuetify

WORKDIR /src/tira/frontend-vuetify

RUN yarn install \
	&& yarn build \
	&& mv node_modules /vuetify-dependencies-node-modules \
	&& rm -Rf *

