FROM webis/tira-application:0.0.43

RUN git clone https://i:kUNzs6xVvaCsfd7Y64-B@git.webis.de/code-research/web-search/chatnoir/chatnoir-web.git /tira/application/src/chatnoir

RUN cd /tira/application/src/chatnoir/chatnoir_ui \
	&& npm install \
	&& npm run build \
	&& apk add lz4-dev re2-dev make cmake uchardet uchardet-dev \
	&& git clone https://github.com/lexbor/lexbor.git /lexbor \
	&& cd /lexbor \
        && cmake . -DLEXBOR_BUILD_TESTS=ON -DLEXBOR_BUILD_EXAMPLES=ON -DLEXBOR_BUILD_SEPARATELY=ON \
        && make \
        && make test \
	&& make install

RUN cd /tira/application/src/chatnoir/chatnoir \
	&& pip3 install -r requirements.txt 

