FROM webis/tira-application:0.0.43

RUN git clone https://i:kUNzs6xVvaCsfd7Y64-B@git.webis.de/code-research/web-search/chatnoir/chatnoir-web.git /tira/application/src/chatnoir

RUN cd /tira/application/src/chatnoir/chatnoir_ui \
	&& npm install \
	&& npm run build \
	&& apk add lz4-dev re2-dev make cmake uchardet uchardet-dev \
	&& git clone https://github.com/lexbor/lexbor.git /lexbor \
	&& cd /lexbor \
        && cmake . -DLEXBOR_BUILD_TESTS=ON -DLEXBOR_BUILD_EXAMPLES=ON -DLEXBOR_BUILD_SEPARATELY=ON \
        && make \
        && make test \
	&& make install

WORKDIR /tira/application/src/chatnoir/chatnoir/

RUN pip3 install -r requirements.txt \
        && cp chatnoir/local_settings.example.py chatnoir/local_settings.py \
	&& ./manage.py createcachetable \
	&& ./manage.py migrate \
	&& pip3 install django-webpack-loader==1.8.1

COPY application/search.py /tira/application/src/chatnoir/chatnoir/chatnoir_search/search.py

ENTRYPOINT ["./manage.py", "runserver", "0.0.0.0:8000"]

