# docker build -t webis/tira-application:basis-0.0.93 -f Dockerfile.application-dev .
FROM ubuntu:22.04

RUN apt-get update \
	&& apt-get upgrade -y \
	&& apt-get install -y python3 python3-pip python-is-python3 mysql-client nginx sudo podman git \
	&& apt-get install -y gcc default-libmysqlclient-dev pkg-config \
	&& rm -Rf /var/cache/apt \
	&& rm -Rf /root/.cache/pip \
	&& echo '%podman ALL=(ALL) ALL' > /etc/sudoers.d/podman

ADD requirements.txt /requirements.txt

RUN pip3 install -r /requirements.txt \
	&& rm -Rf /var/cache/apt \
	&& rm -Rf /root/.cache/pip

RUN useradd -u 1010 tira \
	&& mkdir -p /tira/model/src \
	&& chown tira:tira -R /tira

RUN pip3 uninstall -y diffir \
	&& pip3 install git+https://github.com/mam10eks/diffir

