"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
-----------------------------------------------------------------------------
Options
-----------------------------------------------------------------------------

Becomes the namespace of the generated C++ code
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class User(_message.Message):
    """-----------------------------------------------------------------------------
    Message definitions
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_FIELD_NUMBER: _builtins.int
    USERPW_FIELD_NUMBER: _builtins.int
    ROLES_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    GRAVATARURL_FIELD_NUMBER: _builtins.int
    VIRTUALMACHINEID_FIELD_NUMBER: _builtins.int
    HOST_FIELD_NUMBER: _builtins.int
    VMID_FIELD_NUMBER: _builtins.int
    VMNAME_FIELD_NUMBER: _builtins.int
    ADMINNAME_FIELD_NUMBER: _builtins.int
    ADMINPW_FIELD_NUMBER: _builtins.int
    IP_FIELD_NUMBER: _builtins.int
    PORTSSH_FIELD_NUMBER: _builtins.int
    PORTRDP_FIELD_NUMBER: _builtins.int
    userName: _builtins.str
    userPw: _builtins.str
    email: _builtins.str
    gravatarUrl: _builtins.str
    virtualMachineId: _builtins.str
    host: _builtins.str
    """deprecated: moved to model/virtual-machines"""
    vmId: _builtins.str
    vmName: _builtins.str
    adminName: _builtins.str
    adminPw: _builtins.str
    ip: _builtins.str
    portSsh: _builtins.str
    portRdp: _builtins.str
    @_builtins.property
    def roles(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        userName: _builtins.str | None = ...,
        userPw: _builtins.str | None = ...,
        roles: _abc.Iterable[_builtins.str] | None = ...,
        email: _builtins.str | None = ...,
        gravatarUrl: _builtins.str | None = ...,
        virtualMachineId: _builtins.str | None = ...,
        host: _builtins.str | None = ...,
        vmId: _builtins.str | None = ...,
        vmName: _builtins.str | None = ...,
        adminName: _builtins.str | None = ...,
        adminPw: _builtins.str | None = ...,
        ip: _builtins.str | None = ...,
        portSsh: _builtins.str | None = ...,
        portRdp: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["adminName", b"adminName", "adminPw", b"adminPw", "email", b"email", "gravatarUrl", b"gravatarUrl", "host", b"host", "ip", b"ip", "portRdp", b"portRdp", "portSsh", b"portSsh", "userName", b"userName", "userPw", b"userPw", "virtualMachineId", b"virtualMachineId", "vmId", b"vmId", "vmName", b"vmName"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["adminName", b"adminName", "adminPw", b"adminPw", "email", b"email", "gravatarUrl", b"gravatarUrl", "host", b"host", "ip", b"ip", "portRdp", b"portRdp", "portSsh", b"portSsh", "roles", b"roles", "userName", b"userName", "userPw", b"userPw", "virtualMachineId", b"virtualMachineId", "vmId", b"vmId", "vmName", b"vmName"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___User: _TypeAlias = User  # noqa: Y015

@_typing.final
class Users(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def users(self) -> _containers.RepeatedCompositeFieldContainer[Global___User]: ...
    def __init__(
        self,
        *,
        users: _abc.Iterable[Global___User] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["users", b"users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Users: _TypeAlias = Users  # noqa: Y015

@_typing.final
class VirtualMachine(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIRTUALMACHINEID_FIELD_NUMBER: _builtins.int
    HOST_FIELD_NUMBER: _builtins.int
    VMID_FIELD_NUMBER: _builtins.int
    VMNAME_FIELD_NUMBER: _builtins.int
    ADMINNAME_FIELD_NUMBER: _builtins.int
    ADMINPW_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    USERPW_FIELD_NUMBER: _builtins.int
    IP_FIELD_NUMBER: _builtins.int
    PORTSSH_FIELD_NUMBER: _builtins.int
    PORTRDP_FIELD_NUMBER: _builtins.int
    EVALUATORS_FIELD_NUMBER: _builtins.int
    virtualMachineId: _builtins.str
    host: _builtins.str
    vmId: _builtins.str
    vmName: _builtins.str
    adminName: _builtins.str
    adminPw: _builtins.str
    userName: _builtins.str
    userPw: _builtins.str
    ip: _builtins.str
    portSsh: _builtins.str
    portRdp: _builtins.str
    @_builtins.property
    def evaluators(self) -> _containers.RepeatedCompositeFieldContainer[Global___Evaluator]: ...
    def __init__(
        self,
        *,
        virtualMachineId: _builtins.str | None = ...,
        host: _builtins.str | None = ...,
        vmId: _builtins.str | None = ...,
        vmName: _builtins.str | None = ...,
        adminName: _builtins.str | None = ...,
        adminPw: _builtins.str | None = ...,
        userName: _builtins.str | None = ...,
        userPw: _builtins.str | None = ...,
        ip: _builtins.str | None = ...,
        portSsh: _builtins.str | None = ...,
        portRdp: _builtins.str | None = ...,
        evaluators: _abc.Iterable[Global___Evaluator] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["adminName", b"adminName", "adminPw", b"adminPw", "host", b"host", "ip", b"ip", "portRdp", b"portRdp", "portSsh", b"portSsh", "userName", b"userName", "userPw", b"userPw", "virtualMachineId", b"virtualMachineId", "vmId", b"vmId", "vmName", b"vmName"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["adminName", b"adminName", "adminPw", b"adminPw", "evaluators", b"evaluators", "host", b"host", "ip", b"ip", "portRdp", b"portRdp", "portSsh", b"portSsh", "userName", b"userName", "userPw", b"userPw", "virtualMachineId", b"virtualMachineId", "vmId", b"vmId", "vmName", b"vmName"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VirtualMachine: _TypeAlias = VirtualMachine  # noqa: Y015

@_typing.final
class Dataset(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATASETID_FIELD_NUMBER: _builtins.int
    DISPLAYNAME_FIELD_NUMBER: _builtins.int
    EVALUATORID_FIELD_NUMBER: _builtins.int
    ISCONFIDENTIAL_FIELD_NUMBER: _builtins.int
    ISDEPRECATED_FIELD_NUMBER: _builtins.int
    DATASERVER_FIELD_NUMBER: _builtins.int
    datasetId: _builtins.str
    displayName: _builtins.str
    evaluatorId: _builtins.str
    isConfidential: _builtins.bool
    isDeprecated: _builtins.bool
    dataServer: _builtins.str
    def __init__(
        self,
        *,
        datasetId: _builtins.str | None = ...,
        displayName: _builtins.str | None = ...,
        evaluatorId: _builtins.str | None = ...,
        isConfidential: _builtins.bool | None = ...,
        isDeprecated: _builtins.bool | None = ...,
        dataServer: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dataServer", b"dataServer", "datasetId", b"datasetId", "displayName", b"displayName", "evaluatorId", b"evaluatorId", "isConfidential", b"isConfidential", "isDeprecated", b"isDeprecated"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dataServer", b"dataServer", "datasetId", b"datasetId", "displayName", b"displayName", "evaluatorId", b"evaluatorId", "isConfidential", b"isConfidential", "isDeprecated", b"isDeprecated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Dataset: _TypeAlias = Dataset  # noqa: Y015

@_typing.final
class Evaluator(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EVALUATORID_FIELD_NUMBER: _builtins.int
    COMMAND_FIELD_NUMBER: _builtins.int
    WORKINGDIRECTORY_FIELD_NUMBER: _builtins.int
    MEASURES_FIELD_NUMBER: _builtins.int
    MEASUREKEYS_FIELD_NUMBER: _builtins.int
    MEASUREFILTER_FIELD_NUMBER: _builtins.int
    ISDEPRECATED_FIELD_NUMBER: _builtins.int
    evaluatorId: _builtins.str
    command: _builtins.str
    workingDirectory: _builtins.str
    measures: _builtins.str
    isDeprecated: _builtins.bool
    @_builtins.property
    def measureKeys(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def measureFilter(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """deprecated: superseded by measureKeys."""

    def __init__(
        self,
        *,
        evaluatorId: _builtins.str | None = ...,
        command: _builtins.str | None = ...,
        workingDirectory: _builtins.str | None = ...,
        measures: _builtins.str | None = ...,
        measureKeys: _abc.Iterable[_builtins.str] | None = ...,
        measureFilter: _abc.Iterable[_builtins.str] | None = ...,
        isDeprecated: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "evaluatorId", b"evaluatorId", "isDeprecated", b"isDeprecated", "measures", b"measures", "workingDirectory", b"workingDirectory"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "evaluatorId", b"evaluatorId", "isDeprecated", b"isDeprecated", "measureFilter", b"measureFilter", "measureKeys", b"measureKeys", "measures", b"measures", "workingDirectory", b"workingDirectory"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Evaluator: _TypeAlias = Evaluator  # noqa: Y015

@_typing.final
class Tasks(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Task(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class TaskStatistics(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            PARTICIPANTS_FIELD_NUMBER: _builtins.int
            SOFTWARES_FIELD_NUMBER: _builtins.int
            SOFTWARESRUNNING_FIELD_NUMBER: _builtins.int
            SHOWSOFTWARESRUNNING_FIELD_NUMBER: _builtins.int
            RUNS_FIELD_NUMBER: _builtins.int
            participants: _builtins.int
            softwares: _builtins.int
            softwaresRunning: _builtins.int
            showSoftwaresRunning: _builtins.bool
            runs: _builtins.int
            def __init__(
                self,
                *,
                participants: _builtins.int | None = ...,
                softwares: _builtins.int | None = ...,
                softwaresRunning: _builtins.int | None = ...,
                showSoftwaresRunning: _builtins.bool | None = ...,
                runs: _builtins.int | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["participants", b"participants", "runs", b"runs", "showSoftwaresRunning", b"showSoftwaresRunning", "softwares", b"softwares", "softwaresRunning", b"softwaresRunning"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["participants", b"participants", "runs", b"runs", "showSoftwaresRunning", b"showSoftwaresRunning", "softwares", b"softwares", "softwaresRunning", b"softwaresRunning"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        TASKID_FIELD_NUMBER: _builtins.int
        TASKNAME_FIELD_NUMBER: _builtins.int
        TASKDESCRIPTION_FIELD_NUMBER: _builtins.int
        TRAININGDATASET_FIELD_NUMBER: _builtins.int
        TESTDATASET_FIELD_NUMBER: _builtins.int
        VIRTUALMACHINEID_FIELD_NUMBER: _builtins.int
        HOSTID_FIELD_NUMBER: _builtins.int
        WEB_FIELD_NUMBER: _builtins.int
        TASKSTATISTICS_FIELD_NUMBER: _builtins.int
        ALLOWEDSERVERS_FIELD_NUMBER: _builtins.int
        MAXSTDOUTCHARSONTESTDATA_FIELD_NUMBER: _builtins.int
        MAXSTDERRCHARSONTESTDATA_FIELD_NUMBER: _builtins.int
        MAXFILELISTCHARSONTESTDATA_FIELD_NUMBER: _builtins.int
        COMMANDPLACEHOLDER_FIELD_NUMBER: _builtins.int
        COMMANDDESCRIPTION_FIELD_NUMBER: _builtins.int
        DATASETLABEL_FIELD_NUMBER: _builtins.int
        MAXSTDOUTCHARSONTESTDATAEVAL_FIELD_NUMBER: _builtins.int
        MAXSTDERRCHARSONTESTDATAEVAL_FIELD_NUMBER: _builtins.int
        MAXFILELISTCHARSONTESTDATAEVAL_FIELD_NUMBER: _builtins.int
        taskId: _builtins.str
        taskName: _builtins.str
        taskDescription: _builtins.str
        virtualMachineId: _builtins.str
        hostId: _builtins.str
        web: _builtins.str
        maxStdOutCharsOnTestData: _builtins.int
        maxStdErrCharsOnTestData: _builtins.int
        maxFileListCharsOnTestData: _builtins.int
        commandPlaceholder: _builtins.str
        commandDescription: _builtins.str
        datasetLabel: _builtins.str
        maxStdOutCharsOnTestDataEval: _builtins.int
        maxStdErrCharsOnTestDataEval: _builtins.int
        maxFileListCharsOnTestDataEval: _builtins.int
        @_builtins.property
        def trainingDataset(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        @_builtins.property
        def testDataset(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        @_builtins.property
        def taskStatistics(self) -> Global___Tasks.Task.TaskStatistics: ...
        @_builtins.property
        def allowedServers(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        def __init__(
            self,
            *,
            taskId: _builtins.str | None = ...,
            taskName: _builtins.str | None = ...,
            taskDescription: _builtins.str | None = ...,
            trainingDataset: _abc.Iterable[_builtins.str] | None = ...,
            testDataset: _abc.Iterable[_builtins.str] | None = ...,
            virtualMachineId: _builtins.str | None = ...,
            hostId: _builtins.str | None = ...,
            web: _builtins.str | None = ...,
            taskStatistics: Global___Tasks.Task.TaskStatistics | None = ...,
            allowedServers: _abc.Iterable[_builtins.str] | None = ...,
            maxStdOutCharsOnTestData: _builtins.int | None = ...,
            maxStdErrCharsOnTestData: _builtins.int | None = ...,
            maxFileListCharsOnTestData: _builtins.int | None = ...,
            commandPlaceholder: _builtins.str | None = ...,
            commandDescription: _builtins.str | None = ...,
            datasetLabel: _builtins.str | None = ...,
            maxStdOutCharsOnTestDataEval: _builtins.int | None = ...,
            maxStdErrCharsOnTestDataEval: _builtins.int | None = ...,
            maxFileListCharsOnTestDataEval: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["commandDescription", b"commandDescription", "commandPlaceholder", b"commandPlaceholder", "datasetLabel", b"datasetLabel", "hostId", b"hostId", "maxFileListCharsOnTestData", b"maxFileListCharsOnTestData", "maxFileListCharsOnTestDataEval", b"maxFileListCharsOnTestDataEval", "maxStdErrCharsOnTestData", b"maxStdErrCharsOnTestData", "maxStdErrCharsOnTestDataEval", b"maxStdErrCharsOnTestDataEval", "maxStdOutCharsOnTestData", b"maxStdOutCharsOnTestData", "maxStdOutCharsOnTestDataEval", b"maxStdOutCharsOnTestDataEval", "taskDescription", b"taskDescription", "taskId", b"taskId", "taskName", b"taskName", "taskStatistics", b"taskStatistics", "virtualMachineId", b"virtualMachineId", "web", b"web"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["allowedServers", b"allowedServers", "commandDescription", b"commandDescription", "commandPlaceholder", b"commandPlaceholder", "datasetLabel", b"datasetLabel", "hostId", b"hostId", "maxFileListCharsOnTestData", b"maxFileListCharsOnTestData", "maxFileListCharsOnTestDataEval", b"maxFileListCharsOnTestDataEval", "maxStdErrCharsOnTestData", b"maxStdErrCharsOnTestData", "maxStdErrCharsOnTestDataEval", b"maxStdErrCharsOnTestDataEval", "maxStdOutCharsOnTestData", b"maxStdOutCharsOnTestData", "maxStdOutCharsOnTestDataEval", b"maxStdOutCharsOnTestDataEval", "taskDescription", b"taskDescription", "taskId", b"taskId", "taskName", b"taskName", "taskStatistics", b"taskStatistics", "testDataset", b"testDataset", "trainingDataset", b"trainingDataset", "virtualMachineId", b"virtualMachineId", "web", b"web"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TASKS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tasks(self) -> _containers.RepeatedCompositeFieldContainer[Global___Tasks.Task]: ...
    def __init__(
        self,
        *,
        tasks: _abc.Iterable[Global___Tasks.Task] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tasks", b"tasks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Tasks: _TypeAlias = Tasks  # noqa: Y015

@_typing.final
class Softwares(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Software(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ID_FIELD_NUMBER: _builtins.int
        COUNT_FIELD_NUMBER: _builtins.int
        COMMAND_FIELD_NUMBER: _builtins.int
        WORKINGDIRECTORY_FIELD_NUMBER: _builtins.int
        DATASET_FIELD_NUMBER: _builtins.int
        RUN_FIELD_NUMBER: _builtins.int
        CREATIONDATE_FIELD_NUMBER: _builtins.int
        LASTEDITDATE_FIELD_NUMBER: _builtins.int
        DELETED_FIELD_NUMBER: _builtins.int
        id: _builtins.str
        count: _builtins.str
        command: _builtins.str
        workingDirectory: _builtins.str
        dataset: _builtins.str
        run: _builtins.str
        creationDate: _builtins.str
        lastEditDate: _builtins.str
        deleted: _builtins.bool
        def __init__(
            self,
            *,
            id: _builtins.str | None = ...,
            count: _builtins.str | None = ...,
            command: _builtins.str | None = ...,
            workingDirectory: _builtins.str | None = ...,
            dataset: _builtins.str | None = ...,
            run: _builtins.str | None = ...,
            creationDate: _builtins.str | None = ...,
            lastEditDate: _builtins.str | None = ...,
            deleted: _builtins.bool | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "count", b"count", "creationDate", b"creationDate", "dataset", b"dataset", "deleted", b"deleted", "id", b"id", "lastEditDate", b"lastEditDate", "run", b"run", "workingDirectory", b"workingDirectory"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "count", b"count", "creationDate", b"creationDate", "dataset", b"dataset", "deleted", b"deleted", "id", b"id", "lastEditDate", b"lastEditDate", "run", b"run", "workingDirectory", b"workingDirectory"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SOFTWARES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def softwares(self) -> _containers.RepeatedCompositeFieldContainer[Global___Softwares.Software]: ...
    def __init__(
        self,
        *,
        softwares: _abc.Iterable[Global___Softwares.Software] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["softwares", b"softwares"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Softwares: _TypeAlias = Softwares  # noqa: Y015

@_typing.final
class Evaluation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Measure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str | None = ...,
            value: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    MEASURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def measure(self) -> _containers.RepeatedCompositeFieldContainer[Global___Evaluation.Measure]: ...
    def __init__(
        self,
        *,
        measure: _abc.Iterable[Global___Evaluation.Measure] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["measure", b"measure"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Evaluation: _TypeAlias = Evaluation  # noqa: Y015

@_typing.final
class Run(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SOFTWAREID_FIELD_NUMBER: _builtins.int
    RUNID_FIELD_NUMBER: _builtins.int
    INPUTDATASET_FIELD_NUMBER: _builtins.int
    INPUTRUN_FIELD_NUMBER: _builtins.int
    DOWNLOADABLE_FIELD_NUMBER: _builtins.int
    DELETED_FIELD_NUMBER: _builtins.int
    TASKID_FIELD_NUMBER: _builtins.int
    ACCESSTOKEN_FIELD_NUMBER: _builtins.int
    softwareId: _builtins.str
    runId: _builtins.str
    inputDataset: _builtins.str
    inputRun: _builtins.str
    downloadable: _builtins.bool
    deleted: _builtins.bool
    taskId: _builtins.str
    accessToken: _builtins.str
    def __init__(
        self,
        *,
        softwareId: _builtins.str | None = ...,
        runId: _builtins.str | None = ...,
        inputDataset: _builtins.str | None = ...,
        inputRun: _builtins.str | None = ...,
        downloadable: _builtins.bool | None = ...,
        deleted: _builtins.bool | None = ...,
        taskId: _builtins.str | None = ...,
        accessToken: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["accessToken", b"accessToken", "deleted", b"deleted", "downloadable", b"downloadable", "inputDataset", b"inputDataset", "inputRun", b"inputRun", "runId", b"runId", "softwareId", b"softwareId", "taskId", b"taskId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accessToken", b"accessToken", "deleted", b"deleted", "downloadable", b"downloadable", "inputDataset", b"inputDataset", "inputRun", b"inputRun", "runId", b"runId", "softwareId", b"softwareId", "taskId", b"taskId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Run: _TypeAlias = Run  # noqa: Y015

@_typing.final
class RunReview(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUNID_FIELD_NUMBER: _builtins.int
    REVIEWERID_FIELD_NUMBER: _builtins.int
    REVIEWDATE_FIELD_NUMBER: _builtins.int
    NOERRORS_FIELD_NUMBER: _builtins.int
    MISSINGOUTPUT_FIELD_NUMBER: _builtins.int
    EXTRANEOUSOUTPUT_FIELD_NUMBER: _builtins.int
    INVALIDOUTPUT_FIELD_NUMBER: _builtins.int
    HASERROROUTPUT_FIELD_NUMBER: _builtins.int
    OTHERERRORS_FIELD_NUMBER: _builtins.int
    COMMENT_FIELD_NUMBER: _builtins.int
    HASERRORS_FIELD_NUMBER: _builtins.int
    HASWARNINGS_FIELD_NUMBER: _builtins.int
    HASNOERRORS_FIELD_NUMBER: _builtins.int
    PUBLISHED_FIELD_NUMBER: _builtins.int
    BLINDED_FIELD_NUMBER: _builtins.int
    runId: _builtins.str
    reviewerId: _builtins.str
    reviewDate: _builtins.str
    noErrors: _builtins.bool
    missingOutput: _builtins.bool
    extraneousOutput: _builtins.bool
    invalidOutput: _builtins.bool
    hasErrorOutput: _builtins.bool
    otherErrors: _builtins.bool
    comment: _builtins.str
    hasErrors: _builtins.bool
    hasWarnings: _builtins.bool
    hasNoErrors: _builtins.bool
    published: _builtins.bool
    blinded: _builtins.bool
    def __init__(
        self,
        *,
        runId: _builtins.str | None = ...,
        reviewerId: _builtins.str | None = ...,
        reviewDate: _builtins.str | None = ...,
        noErrors: _builtins.bool | None = ...,
        missingOutput: _builtins.bool | None = ...,
        extraneousOutput: _builtins.bool | None = ...,
        invalidOutput: _builtins.bool | None = ...,
        hasErrorOutput: _builtins.bool | None = ...,
        otherErrors: _builtins.bool | None = ...,
        comment: _builtins.str | None = ...,
        hasErrors: _builtins.bool | None = ...,
        hasWarnings: _builtins.bool | None = ...,
        hasNoErrors: _builtins.bool | None = ...,
        published: _builtins.bool | None = ...,
        blinded: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["blinded", b"blinded", "comment", b"comment", "extraneousOutput", b"extraneousOutput", "hasErrorOutput", b"hasErrorOutput", "hasErrors", b"hasErrors", "hasNoErrors", b"hasNoErrors", "hasWarnings", b"hasWarnings", "invalidOutput", b"invalidOutput", "missingOutput", b"missingOutput", "noErrors", b"noErrors", "otherErrors", b"otherErrors", "published", b"published", "reviewDate", b"reviewDate", "reviewerId", b"reviewerId", "runId", b"runId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blinded", b"blinded", "comment", b"comment", "extraneousOutput", b"extraneousOutput", "hasErrorOutput", b"hasErrorOutput", "hasErrors", b"hasErrors", "hasNoErrors", b"hasNoErrors", "hasWarnings", b"hasWarnings", "invalidOutput", b"invalidOutput", "missingOutput", b"missingOutput", "noErrors", b"noErrors", "otherErrors", b"otherErrors", "published", b"published", "reviewDate", b"reviewDate", "reviewerId", b"reviewerId", "runId", b"runId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RunReview: _TypeAlias = RunReview  # noqa: Y015
