"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
-----------------------------------------------------------------------------
Options
-----------------------------------------------------------------------------

Becomes the namespace of the generated C++ code
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class User(_message.Message):
    """-----------------------------------------------------------------------------
    Message definitions
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_FIELD_NUMBER: _builtins.int
    USERPW_FIELD_NUMBER: _builtins.int
    ROLES_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    GRAVATARURL_FIELD_NUMBER: _builtins.int
    VIRTUALMACHINEID_FIELD_NUMBER: _builtins.int
    HOST_FIELD_NUMBER: _builtins.int
    VMID_FIELD_NUMBER: _builtins.int
    VMNAME_FIELD_NUMBER: _builtins.int
    ADMINNAME_FIELD_NUMBER: _builtins.int
    ADMINPW_FIELD_NUMBER: _builtins.int
    IP_FIELD_NUMBER: _builtins.int
    PORTSSH_FIELD_NUMBER: _builtins.int
    PORTRDP_FIELD_NUMBER: _builtins.int
    userName: _builtins.str
    userPw: _builtins.str
    email: _builtins.str
    gravatarUrl: _builtins.str
    virtualMachineId: _builtins.str
    host: _builtins.str
    """deprecated: moved to model/virtual-machines"""
    vmId: _builtins.str
    vmName: _builtins.str
    adminName: _builtins.str
    adminPw: _builtins.str
    ip: _builtins.str
    portSsh: _builtins.str
    portRdp: _builtins.str
    @_builtins.property
    def roles(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        userName: _builtins.str | None = ...,
        userPw: _builtins.str | None = ...,
        roles: _abc.Iterable[_builtins.str] | None = ...,
        email: _builtins.str | None = ...,
        gravatarUrl: _builtins.str | None = ...,
        virtualMachineId: _builtins.str | None = ...,
        host: _builtins.str | None = ...,
        vmId: _builtins.str | None = ...,
        vmName: _builtins.str | None = ...,
        adminName: _builtins.str | None = ...,
        adminPw: _builtins.str | None = ...,
        ip: _builtins.str | None = ...,
        portSsh: _builtins.str | None = ...,
        portRdp: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["adminName", b"adminName", "adminPw", b"adminPw", "email", b"email", "gravatarUrl", b"gravatarUrl", "host", b"host", "ip", b"ip", "portRdp", b"portRdp", "portSsh", b"portSsh", "userName", b"userName", "userPw", b"userPw", "virtualMachineId", b"virtualMachineId", "vmId", b"vmId", "vmName", b"vmName"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["adminName", b"adminName", "adminPw", b"adminPw", "email", b"email", "gravatarUrl", b"gravatarUrl", "host", b"host", "ip", b"ip", "portRdp", b"portRdp", "portSsh", b"portSsh", "roles", b"roles", "userName", b"userName", "userPw", b"userPw", "virtualMachineId", b"virtualMachineId", "vmId", b"vmId", "vmName", b"vmName"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___User: _TypeAlias = User  # noqa: Y015

@_typing.final
class Users(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def users(self) -> _containers.RepeatedCompositeFieldContainer[Global___User]: ...
    def __init__(
        self,
        *,
        users: _abc.Iterable[Global___User] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["users", b"users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Users: _TypeAlias = Users  # noqa: Y015

@_typing.final
class VirtualMachine(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIRTUALMACHINEID_FIELD_NUMBER: _builtins.int
    HOST_FIELD_NUMBER: _builtins.int
    VMID_FIELD_NUMBER: _builtins.int
    VMNAME_FIELD_NUMBER: _builtins.int
    ADMINNAME_FIELD_NUMBER: _builtins.int
    ADMINPW_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    USERPW_FIELD_NUMBER: _builtins.int
    IP_FIELD_NUMBER: _builtins.int
    PORTSSH_FIELD_NUMBER: _builtins.int
    PORTRDP_FIELD_NUMBER: _builtins.int
    EVALUATORS_FIELD_NUMBER: _builtins.int
    virtualMachineId: _builtins.str
    host: _builtins.str
    vmId: _builtins.str
    vmName: _builtins.str
    adminName: _builtins.str
    adminPw: _builtins.str
    userName: _builtins.str
    userPw: _builtins.str
    ip: _builtins.str
    portSsh: _builtins.str
    portRdp: _builtins.str
    @_builtins.property
    def evaluators(self) -> _containers.RepeatedCompositeFieldContainer[Global___Evaluator]: ...
    def __init__(
        self,
        *,
        virtualMachineId: _builtins.str | None = ...,
        host: _builtins.str | None = ...,
        vmId: _builtins.str | None = ...,
        vmName: _builtins.str | None = ...,
        adminName: _builtins.str | None = ...,
        adminPw: _builtins.str | None = ...,
        userName: _builtins.str | None = ...,
        userPw: _builtins.str | None = ...,
        ip: _builtins.str | None = ...,
        portSsh: _builtins.str | None = ...,
        portRdp: _builtins.str | None = ...,
        evaluators: _abc.Iterable[Global___Evaluator] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["adminName", b"adminName", "adminPw", b"adminPw", "host", b"host", "ip", b"ip", "portRdp", b"portRdp", "portSsh", b"portSsh", "userName", b"userName", "userPw", b"userPw", "virtualMachineId", b"virtualMachineId", "vmId", b"vmId", "vmName", b"vmName"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["adminName", b"adminName", "adminPw", b"adminPw", "evaluators", b"evaluators", "host", b"host", "ip", b"ip", "portRdp", b"portRdp", "portSsh", b"portSsh", "userName", b"userName", "userPw", b"userPw", "virtualMachineId", b"virtualMachineId", "vmId", b"vmId", "vmName", b"vmName"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VirtualMachine: _TypeAlias = VirtualMachine  # noqa: Y015

@_typing.final
class VirtualMachineState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    GUESTOS_FIELD_NUMBER: _builtins.int
    MEMORYSIZE_FIELD_NUMBER: _builtins.int
    NUMBEROFCPUS_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    STATERUNNING_FIELD_NUMBER: _builtins.int
    STATESANDBOXED_FIELD_NUMBER: _builtins.int
    STATESANDBOXING_FIELD_NUMBER: _builtins.int
    STATEUNSANDBOXING_FIELD_NUMBER: _builtins.int
    HOST_FIELD_NUMBER: _builtins.int
    PORTSSH_FIELD_NUMBER: _builtins.int
    PORTRDP_FIELD_NUMBER: _builtins.int
    PORTSSHOPEN_FIELD_NUMBER: _builtins.int
    PORTRDPOPEN_FIELD_NUMBER: _builtins.int
    PROCESSRUNNING_FIELD_NUMBER: _builtins.int
    PROCESSTYPE_FIELD_NUMBER: _builtins.int
    PROCESSRUNID_FIELD_NUMBER: _builtins.int
    PROCESSSTATE_FIELD_NUMBER: _builtins.int
    PROCESSTIME_FIELD_NUMBER: _builtins.int
    VMBOOTING_FIELD_NUMBER: _builtins.int
    VMPOWERINGOFF_FIELD_NUMBER: _builtins.int
    VMSHUTTINGDOWN_FIELD_NUMBER: _builtins.int
    SOFTWARE_FIELD_NUMBER: _builtins.int
    RUN_FIELD_NUMBER: _builtins.int
    HASLATESTOUTPUT_FIELD_NUMBER: _builtins.int
    LATESTOUTPUT_FIELD_NUMBER: _builtins.int
    guestOs: _builtins.str
    memorySize: _builtins.str
    numberOfCpus: _builtins.str
    state: _builtins.str
    stateRunning: _builtins.bool
    stateSandboxed: _builtins.bool
    stateSandboxing: _builtins.bool
    stateUnsandboxing: _builtins.bool
    host: _builtins.str
    portSsh: _builtins.str
    portRdp: _builtins.str
    portSshOpen: _builtins.bool
    portRdpOpen: _builtins.bool
    processRunning: _builtins.bool
    processType: _builtins.str
    processRunId: _builtins.str
    processState: _builtins.str
    processTime: _builtins.str
    vmBooting: _builtins.bool
    vmPoweringOff: _builtins.bool
    vmShuttingDown: _builtins.bool
    hasLatestOutput: _builtins.bool
    latestOutput: _builtins.str
    @_builtins.property
    def software(self) -> Global___Softwares.Software: ...
    @_builtins.property
    def run(self) -> Global___Run: ...
    def __init__(
        self,
        *,
        guestOs: _builtins.str | None = ...,
        memorySize: _builtins.str | None = ...,
        numberOfCpus: _builtins.str | None = ...,
        state: _builtins.str | None = ...,
        stateRunning: _builtins.bool | None = ...,
        stateSandboxed: _builtins.bool | None = ...,
        stateSandboxing: _builtins.bool | None = ...,
        stateUnsandboxing: _builtins.bool | None = ...,
        host: _builtins.str | None = ...,
        portSsh: _builtins.str | None = ...,
        portRdp: _builtins.str | None = ...,
        portSshOpen: _builtins.bool | None = ...,
        portRdpOpen: _builtins.bool | None = ...,
        processRunning: _builtins.bool | None = ...,
        processType: _builtins.str | None = ...,
        processRunId: _builtins.str | None = ...,
        processState: _builtins.str | None = ...,
        processTime: _builtins.str | None = ...,
        vmBooting: _builtins.bool | None = ...,
        vmPoweringOff: _builtins.bool | None = ...,
        vmShuttingDown: _builtins.bool | None = ...,
        software: Global___Softwares.Software | None = ...,
        run: Global___Run | None = ...,
        hasLatestOutput: _builtins.bool | None = ...,
        latestOutput: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["guestOs", b"guestOs", "hasLatestOutput", b"hasLatestOutput", "host", b"host", "latestOutput", b"latestOutput", "memorySize", b"memorySize", "numberOfCpus", b"numberOfCpus", "portRdp", b"portRdp", "portRdpOpen", b"portRdpOpen", "portSsh", b"portSsh", "portSshOpen", b"portSshOpen", "processRunId", b"processRunId", "processRunning", b"processRunning", "processState", b"processState", "processTime", b"processTime", "processType", b"processType", "run", b"run", "software", b"software", "state", b"state", "stateRunning", b"stateRunning", "stateSandboxed", b"stateSandboxed", "stateSandboxing", b"stateSandboxing", "stateUnsandboxing", b"stateUnsandboxing", "vmBooting", b"vmBooting", "vmPoweringOff", b"vmPoweringOff", "vmShuttingDown", b"vmShuttingDown"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["guestOs", b"guestOs", "hasLatestOutput", b"hasLatestOutput", "host", b"host", "latestOutput", b"latestOutput", "memorySize", b"memorySize", "numberOfCpus", b"numberOfCpus", "portRdp", b"portRdp", "portRdpOpen", b"portRdpOpen", "portSsh", b"portSsh", "portSshOpen", b"portSshOpen", "processRunId", b"processRunId", "processRunning", b"processRunning", "processState", b"processState", "processTime", b"processTime", "processType", b"processType", "run", b"run", "software", b"software", "state", b"state", "stateRunning", b"stateRunning", "stateSandboxed", b"stateSandboxed", "stateSandboxing", b"stateSandboxing", "stateUnsandboxing", b"stateUnsandboxing", "vmBooting", b"vmBooting", "vmPoweringOff", b"vmPoweringOff", "vmShuttingDown", b"vmShuttingDown"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VirtualMachineState: _TypeAlias = VirtualMachineState  # noqa: Y015

@_typing.final
class VirtualMachineState2(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASKVM_FIELD_NUMBER: _builtins.int
    PORTSSHOPEN_FIELD_NUMBER: _builtins.int
    PORTRDPOPEN_FIELD_NUMBER: _builtins.int
    portSshOpen: _builtins.bool
    portRdpOpen: _builtins.bool
    @_builtins.property
    def taskVm(self) -> Global___VirtualMachine: ...
    def __init__(
        self,
        *,
        taskVm: Global___VirtualMachine | None = ...,
        portSshOpen: _builtins.bool | None = ...,
        portRdpOpen: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["portRdpOpen", b"portRdpOpen", "portSshOpen", b"portSshOpen", "taskVm", b"taskVm"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["portRdpOpen", b"portRdpOpen", "portSshOpen", b"portSshOpen", "taskVm", b"taskVm"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VirtualMachineState2: _TypeAlias = VirtualMachineState2  # noqa: Y015

@_typing.final
class Hosts(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Host(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        HOSTID_FIELD_NUMBER: _builtins.int
        NAME_FIELD_NUMBER: _builtins.int
        YEARS_FIELD_NUMBER: _builtins.int
        WEB_FIELD_NUMBER: _builtins.int
        TASKS_FIELD_NUMBER: _builtins.int
        hostId: _builtins.str
        name: _builtins.str
        years: _builtins.str
        web: _builtins.str
        @_builtins.property
        def tasks(self) -> _containers.RepeatedCompositeFieldContainer[Global___Tasks.Task]: ...
        def __init__(
            self,
            *,
            hostId: _builtins.str | None = ...,
            name: _builtins.str | None = ...,
            years: _builtins.str | None = ...,
            web: _builtins.str | None = ...,
            tasks: _abc.Iterable[Global___Tasks.Task] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["hostId", b"hostId", "name", b"name", "web", b"web", "years", b"years"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["hostId", b"hostId", "name", b"name", "tasks", b"tasks", "web", b"web", "years", b"years"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    HOSTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def hosts(self) -> _containers.RepeatedCompositeFieldContainer[Global___Hosts.Host]: ...
    def __init__(
        self,
        *,
        hosts: _abc.Iterable[Global___Hosts.Host] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hosts", b"hosts"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Hosts: _TypeAlias = Hosts  # noqa: Y015

@_typing.final
class Dataset(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATASETID_FIELD_NUMBER: _builtins.int
    DISPLAYNAME_FIELD_NUMBER: _builtins.int
    EVALUATORID_FIELD_NUMBER: _builtins.int
    ISCONFIDENTIAL_FIELD_NUMBER: _builtins.int
    ISDEPRECATED_FIELD_NUMBER: _builtins.int
    DATASERVER_FIELD_NUMBER: _builtins.int
    datasetId: _builtins.str
    displayName: _builtins.str
    evaluatorId: _builtins.str
    isConfidential: _builtins.bool
    isDeprecated: _builtins.bool
    dataServer: _builtins.str
    def __init__(
        self,
        *,
        datasetId: _builtins.str | None = ...,
        displayName: _builtins.str | None = ...,
        evaluatorId: _builtins.str | None = ...,
        isConfidential: _builtins.bool | None = ...,
        isDeprecated: _builtins.bool | None = ...,
        dataServer: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dataServer", b"dataServer", "datasetId", b"datasetId", "displayName", b"displayName", "evaluatorId", b"evaluatorId", "isConfidential", b"isConfidential", "isDeprecated", b"isDeprecated"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dataServer", b"dataServer", "datasetId", b"datasetId", "displayName", b"displayName", "evaluatorId", b"evaluatorId", "isConfidential", b"isConfidential", "isDeprecated", b"isDeprecated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Dataset: _TypeAlias = Dataset  # noqa: Y015

@_typing.final
class Evaluator(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EVALUATORID_FIELD_NUMBER: _builtins.int
    COMMAND_FIELD_NUMBER: _builtins.int
    WORKINGDIRECTORY_FIELD_NUMBER: _builtins.int
    MEASURES_FIELD_NUMBER: _builtins.int
    MEASUREKEYS_FIELD_NUMBER: _builtins.int
    MEASUREFILTER_FIELD_NUMBER: _builtins.int
    ISDEPRECATED_FIELD_NUMBER: _builtins.int
    evaluatorId: _builtins.str
    command: _builtins.str
    workingDirectory: _builtins.str
    measures: _builtins.str
    isDeprecated: _builtins.bool
    @_builtins.property
    def measureKeys(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def measureFilter(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """deprecated: superseded by measureKeys."""

    def __init__(
        self,
        *,
        evaluatorId: _builtins.str | None = ...,
        command: _builtins.str | None = ...,
        workingDirectory: _builtins.str | None = ...,
        measures: _builtins.str | None = ...,
        measureKeys: _abc.Iterable[_builtins.str] | None = ...,
        measureFilter: _abc.Iterable[_builtins.str] | None = ...,
        isDeprecated: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "evaluatorId", b"evaluatorId", "isDeprecated", b"isDeprecated", "measures", b"measures", "workingDirectory", b"workingDirectory"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "evaluatorId", b"evaluatorId", "isDeprecated", b"isDeprecated", "measureFilter", b"measureFilter", "measureKeys", b"measureKeys", "measures", b"measures", "workingDirectory", b"workingDirectory"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Evaluator: _TypeAlias = Evaluator  # noqa: Y015

@_typing.final
class Tasks(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Task(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class TaskStatistics(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            PARTICIPANTS_FIELD_NUMBER: _builtins.int
            SOFTWARES_FIELD_NUMBER: _builtins.int
            SOFTWARESRUNNING_FIELD_NUMBER: _builtins.int
            SHOWSOFTWARESRUNNING_FIELD_NUMBER: _builtins.int
            RUNS_FIELD_NUMBER: _builtins.int
            participants: _builtins.int
            softwares: _builtins.int
            softwaresRunning: _builtins.int
            showSoftwaresRunning: _builtins.bool
            runs: _builtins.int
            def __init__(
                self,
                *,
                participants: _builtins.int | None = ...,
                softwares: _builtins.int | None = ...,
                softwaresRunning: _builtins.int | None = ...,
                showSoftwaresRunning: _builtins.bool | None = ...,
                runs: _builtins.int | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["participants", b"participants", "runs", b"runs", "showSoftwaresRunning", b"showSoftwaresRunning", "softwares", b"softwares", "softwaresRunning", b"softwaresRunning"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["participants", b"participants", "runs", b"runs", "showSoftwaresRunning", b"showSoftwaresRunning", "softwares", b"softwares", "softwaresRunning", b"softwaresRunning"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        TASKID_FIELD_NUMBER: _builtins.int
        TASKNAME_FIELD_NUMBER: _builtins.int
        TASKDESCRIPTION_FIELD_NUMBER: _builtins.int
        TRAININGDATASET_FIELD_NUMBER: _builtins.int
        TESTDATASET_FIELD_NUMBER: _builtins.int
        VIRTUALMACHINEID_FIELD_NUMBER: _builtins.int
        HOSTID_FIELD_NUMBER: _builtins.int
        WEB_FIELD_NUMBER: _builtins.int
        TASKSTATISTICS_FIELD_NUMBER: _builtins.int
        ALLOWEDSERVERS_FIELD_NUMBER: _builtins.int
        MAXSTDOUTCHARSONTESTDATA_FIELD_NUMBER: _builtins.int
        MAXSTDERRCHARSONTESTDATA_FIELD_NUMBER: _builtins.int
        MAXFILELISTCHARSONTESTDATA_FIELD_NUMBER: _builtins.int
        COMMANDPLACEHOLDER_FIELD_NUMBER: _builtins.int
        COMMANDDESCRIPTION_FIELD_NUMBER: _builtins.int
        DATASETLABEL_FIELD_NUMBER: _builtins.int
        MAXSTDOUTCHARSONTESTDATAEVAL_FIELD_NUMBER: _builtins.int
        MAXSTDERRCHARSONTESTDATAEVAL_FIELD_NUMBER: _builtins.int
        MAXFILELISTCHARSONTESTDATAEVAL_FIELD_NUMBER: _builtins.int
        taskId: _builtins.str
        taskName: _builtins.str
        taskDescription: _builtins.str
        virtualMachineId: _builtins.str
        hostId: _builtins.str
        web: _builtins.str
        maxStdOutCharsOnTestData: _builtins.int
        maxStdErrCharsOnTestData: _builtins.int
        maxFileListCharsOnTestData: _builtins.int
        commandPlaceholder: _builtins.str
        commandDescription: _builtins.str
        datasetLabel: _builtins.str
        maxStdOutCharsOnTestDataEval: _builtins.int
        maxStdErrCharsOnTestDataEval: _builtins.int
        maxFileListCharsOnTestDataEval: _builtins.int
        @_builtins.property
        def trainingDataset(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        @_builtins.property
        def testDataset(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        @_builtins.property
        def taskStatistics(self) -> Global___Tasks.Task.TaskStatistics: ...
        @_builtins.property
        def allowedServers(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        def __init__(
            self,
            *,
            taskId: _builtins.str | None = ...,
            taskName: _builtins.str | None = ...,
            taskDescription: _builtins.str | None = ...,
            trainingDataset: _abc.Iterable[_builtins.str] | None = ...,
            testDataset: _abc.Iterable[_builtins.str] | None = ...,
            virtualMachineId: _builtins.str | None = ...,
            hostId: _builtins.str | None = ...,
            web: _builtins.str | None = ...,
            taskStatistics: Global___Tasks.Task.TaskStatistics | None = ...,
            allowedServers: _abc.Iterable[_builtins.str] | None = ...,
            maxStdOutCharsOnTestData: _builtins.int | None = ...,
            maxStdErrCharsOnTestData: _builtins.int | None = ...,
            maxFileListCharsOnTestData: _builtins.int | None = ...,
            commandPlaceholder: _builtins.str | None = ...,
            commandDescription: _builtins.str | None = ...,
            datasetLabel: _builtins.str | None = ...,
            maxStdOutCharsOnTestDataEval: _builtins.int | None = ...,
            maxStdErrCharsOnTestDataEval: _builtins.int | None = ...,
            maxFileListCharsOnTestDataEval: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["commandDescription", b"commandDescription", "commandPlaceholder", b"commandPlaceholder", "datasetLabel", b"datasetLabel", "hostId", b"hostId", "maxFileListCharsOnTestData", b"maxFileListCharsOnTestData", "maxFileListCharsOnTestDataEval", b"maxFileListCharsOnTestDataEval", "maxStdErrCharsOnTestData", b"maxStdErrCharsOnTestData", "maxStdErrCharsOnTestDataEval", b"maxStdErrCharsOnTestDataEval", "maxStdOutCharsOnTestData", b"maxStdOutCharsOnTestData", "maxStdOutCharsOnTestDataEval", b"maxStdOutCharsOnTestDataEval", "taskDescription", b"taskDescription", "taskId", b"taskId", "taskName", b"taskName", "taskStatistics", b"taskStatistics", "virtualMachineId", b"virtualMachineId", "web", b"web"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["allowedServers", b"allowedServers", "commandDescription", b"commandDescription", "commandPlaceholder", b"commandPlaceholder", "datasetLabel", b"datasetLabel", "hostId", b"hostId", "maxFileListCharsOnTestData", b"maxFileListCharsOnTestData", "maxFileListCharsOnTestDataEval", b"maxFileListCharsOnTestDataEval", "maxStdErrCharsOnTestData", b"maxStdErrCharsOnTestData", "maxStdErrCharsOnTestDataEval", b"maxStdErrCharsOnTestDataEval", "maxStdOutCharsOnTestData", b"maxStdOutCharsOnTestData", "maxStdOutCharsOnTestDataEval", b"maxStdOutCharsOnTestDataEval", "taskDescription", b"taskDescription", "taskId", b"taskId", "taskName", b"taskName", "taskStatistics", b"taskStatistics", "testDataset", b"testDataset", "trainingDataset", b"trainingDataset", "virtualMachineId", b"virtualMachineId", "web", b"web"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TASKS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tasks(self) -> _containers.RepeatedCompositeFieldContainer[Global___Tasks.Task]: ...
    def __init__(
        self,
        *,
        tasks: _abc.Iterable[Global___Tasks.Task] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tasks", b"tasks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Tasks: _TypeAlias = Tasks  # noqa: Y015

@_typing.final
class Softwares(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Software(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ID_FIELD_NUMBER: _builtins.int
        COUNT_FIELD_NUMBER: _builtins.int
        COMMAND_FIELD_NUMBER: _builtins.int
        WORKINGDIRECTORY_FIELD_NUMBER: _builtins.int
        DATASET_FIELD_NUMBER: _builtins.int
        RUN_FIELD_NUMBER: _builtins.int
        CREATIONDATE_FIELD_NUMBER: _builtins.int
        LASTEDITDATE_FIELD_NUMBER: _builtins.int
        DELETED_FIELD_NUMBER: _builtins.int
        id: _builtins.str
        count: _builtins.str
        command: _builtins.str
        workingDirectory: _builtins.str
        dataset: _builtins.str
        run: _builtins.str
        creationDate: _builtins.str
        lastEditDate: _builtins.str
        deleted: _builtins.bool
        def __init__(
            self,
            *,
            id: _builtins.str | None = ...,
            count: _builtins.str | None = ...,
            command: _builtins.str | None = ...,
            workingDirectory: _builtins.str | None = ...,
            dataset: _builtins.str | None = ...,
            run: _builtins.str | None = ...,
            creationDate: _builtins.str | None = ...,
            lastEditDate: _builtins.str | None = ...,
            deleted: _builtins.bool | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "count", b"count", "creationDate", b"creationDate", "dataset", b"dataset", "deleted", b"deleted", "id", b"id", "lastEditDate", b"lastEditDate", "run", b"run", "workingDirectory", b"workingDirectory"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "count", b"count", "creationDate", b"creationDate", "dataset", b"dataset", "deleted", b"deleted", "id", b"id", "lastEditDate", b"lastEditDate", "run", b"run", "workingDirectory", b"workingDirectory"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SOFTWARES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def softwares(self) -> _containers.RepeatedCompositeFieldContainer[Global___Softwares.Software]: ...
    def __init__(
        self,
        *,
        softwares: _abc.Iterable[Global___Softwares.Software] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["softwares", b"softwares"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Softwares: _TypeAlias = Softwares  # noqa: Y015

@_typing.final
class Evaluation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Measure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str | None = ...,
            value: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    MEASURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def measure(self) -> _containers.RepeatedCompositeFieldContainer[Global___Evaluation.Measure]: ...
    def __init__(
        self,
        *,
        measure: _abc.Iterable[Global___Evaluation.Measure] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["measure", b"measure"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Evaluation: _TypeAlias = Evaluation  # noqa: Y015

@_typing.final
class Run(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SOFTWAREID_FIELD_NUMBER: _builtins.int
    RUNID_FIELD_NUMBER: _builtins.int
    INPUTDATASET_FIELD_NUMBER: _builtins.int
    INPUTRUN_FIELD_NUMBER: _builtins.int
    DOWNLOADABLE_FIELD_NUMBER: _builtins.int
    DELETED_FIELD_NUMBER: _builtins.int
    TASKID_FIELD_NUMBER: _builtins.int
    ACCESSTOKEN_FIELD_NUMBER: _builtins.int
    softwareId: _builtins.str
    runId: _builtins.str
    inputDataset: _builtins.str
    inputRun: _builtins.str
    downloadable: _builtins.bool
    deleted: _builtins.bool
    taskId: _builtins.str
    accessToken: _builtins.str
    def __init__(
        self,
        *,
        softwareId: _builtins.str | None = ...,
        runId: _builtins.str | None = ...,
        inputDataset: _builtins.str | None = ...,
        inputRun: _builtins.str | None = ...,
        downloadable: _builtins.bool | None = ...,
        deleted: _builtins.bool | None = ...,
        taskId: _builtins.str | None = ...,
        accessToken: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["accessToken", b"accessToken", "deleted", b"deleted", "downloadable", b"downloadable", "inputDataset", b"inputDataset", "inputRun", b"inputRun", "runId", b"runId", "softwareId", b"softwareId", "taskId", b"taskId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accessToken", b"accessToken", "deleted", b"deleted", "downloadable", b"downloadable", "inputDataset", b"inputDataset", "inputRun", b"inputRun", "runId", b"runId", "softwareId", b"softwareId", "taskId", b"taskId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Run: _TypeAlias = Run  # noqa: Y015

@_typing.final
class ExtendedRun(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_FIELD_NUMBER: _builtins.int
    STDOUT_FIELD_NUMBER: _builtins.int
    STDERR_FIELD_NUMBER: _builtins.int
    FILELIST_FIELD_NUMBER: _builtins.int
    RUNTIME_FIELD_NUMBER: _builtins.int
    RUNTIMEDETAILS_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    SIZEINBYTES_FIELD_NUMBER: _builtins.int
    NUMLINES_FIELD_NUMBER: _builtins.int
    NUMFILES_FIELD_NUMBER: _builtins.int
    NUMDIRECTORIES_FIELD_NUMBER: _builtins.int
    SOFTWAREDELETED_FIELD_NUMBER: _builtins.int
    INPUTRUNDELETED_FIELD_NUMBER: _builtins.int
    EVALUATIONRUN_FIELD_NUMBER: _builtins.int
    ISRUNNING_FIELD_NUMBER: _builtins.int
    HASREVIEW_FIELD_NUMBER: _builtins.int
    RUNREVIEW_FIELD_NUMBER: _builtins.int
    EVALUATION_FIELD_NUMBER: _builtins.int
    USER_FIELD_NUMBER: _builtins.int
    HASINPUTRUN_FIELD_NUMBER: _builtins.int
    INPUTRUN_FIELD_NUMBER: _builtins.int
    ISDEPRECATED_FIELD_NUMBER: _builtins.int
    INPUTDATASETDEPRECATED_FIELD_NUMBER: _builtins.int
    SOFTWAREDEPRECATED_FIELD_NUMBER: _builtins.int
    stdout: _builtins.str
    stderr: _builtins.str
    fileList: _builtins.str
    runtime: _builtins.str
    runtimeDetails: _builtins.str
    size: _builtins.str
    sizeInBytes: _builtins.str
    numLines: _builtins.str
    numFiles: _builtins.str
    numDirectories: _builtins.str
    softwareDeleted: _builtins.bool
    inputRunDeleted: _builtins.bool
    evaluationRun: _builtins.bool
    isRunning: _builtins.bool
    hasReview: _builtins.bool
    hasInputRun: _builtins.bool
    isDeprecated: _builtins.bool
    inputDatasetDeprecated: _builtins.bool
    softwareDeprecated: _builtins.bool
    @_builtins.property
    def run(self) -> Global___Run: ...
    @_builtins.property
    def runReview(self) -> Global___RunReview: ...
    @_builtins.property
    def evaluation(self) -> Global___Evaluation: ...
    @_builtins.property
    def user(self) -> Global___User: ...
    @_builtins.property
    def inputRun(self) -> Global___ExtendedRun: ...
    def __init__(
        self,
        *,
        run: Global___Run | None = ...,
        stdout: _builtins.str | None = ...,
        stderr: _builtins.str | None = ...,
        fileList: _builtins.str | None = ...,
        runtime: _builtins.str | None = ...,
        runtimeDetails: _builtins.str | None = ...,
        size: _builtins.str | None = ...,
        sizeInBytes: _builtins.str | None = ...,
        numLines: _builtins.str | None = ...,
        numFiles: _builtins.str | None = ...,
        numDirectories: _builtins.str | None = ...,
        softwareDeleted: _builtins.bool | None = ...,
        inputRunDeleted: _builtins.bool | None = ...,
        evaluationRun: _builtins.bool | None = ...,
        isRunning: _builtins.bool | None = ...,
        hasReview: _builtins.bool | None = ...,
        runReview: Global___RunReview | None = ...,
        evaluation: Global___Evaluation | None = ...,
        user: Global___User | None = ...,
        hasInputRun: _builtins.bool | None = ...,
        inputRun: Global___ExtendedRun | None = ...,
        isDeprecated: _builtins.bool | None = ...,
        inputDatasetDeprecated: _builtins.bool | None = ...,
        softwareDeprecated: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["evaluation", b"evaluation", "evaluationRun", b"evaluationRun", "fileList", b"fileList", "hasInputRun", b"hasInputRun", "hasReview", b"hasReview", "inputDatasetDeprecated", b"inputDatasetDeprecated", "inputRun", b"inputRun", "inputRunDeleted", b"inputRunDeleted", "isDeprecated", b"isDeprecated", "isRunning", b"isRunning", "numDirectories", b"numDirectories", "numFiles", b"numFiles", "numLines", b"numLines", "run", b"run", "runReview", b"runReview", "runtime", b"runtime", "runtimeDetails", b"runtimeDetails", "size", b"size", "sizeInBytes", b"sizeInBytes", "softwareDeleted", b"softwareDeleted", "softwareDeprecated", b"softwareDeprecated", "stderr", b"stderr", "stdout", b"stdout", "user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["evaluation", b"evaluation", "evaluationRun", b"evaluationRun", "fileList", b"fileList", "hasInputRun", b"hasInputRun", "hasReview", b"hasReview", "inputDatasetDeprecated", b"inputDatasetDeprecated", "inputRun", b"inputRun", "inputRunDeleted", b"inputRunDeleted", "isDeprecated", b"isDeprecated", "isRunning", b"isRunning", "numDirectories", b"numDirectories", "numFiles", b"numFiles", "numLines", b"numLines", "run", b"run", "runReview", b"runReview", "runtime", b"runtime", "runtimeDetails", b"runtimeDetails", "size", b"size", "sizeInBytes", b"sizeInBytes", "softwareDeleted", b"softwareDeleted", "softwareDeprecated", b"softwareDeprecated", "stderr", b"stderr", "stdout", b"stdout", "user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ExtendedRun: _TypeAlias = ExtendedRun  # noqa: Y015

@_typing.final
class RunReview(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUNID_FIELD_NUMBER: _builtins.int
    REVIEWERID_FIELD_NUMBER: _builtins.int
    REVIEWDATE_FIELD_NUMBER: _builtins.int
    NOERRORS_FIELD_NUMBER: _builtins.int
    MISSINGOUTPUT_FIELD_NUMBER: _builtins.int
    EXTRANEOUSOUTPUT_FIELD_NUMBER: _builtins.int
    INVALIDOUTPUT_FIELD_NUMBER: _builtins.int
    HASERROROUTPUT_FIELD_NUMBER: _builtins.int
    OTHERERRORS_FIELD_NUMBER: _builtins.int
    COMMENT_FIELD_NUMBER: _builtins.int
    HASERRORS_FIELD_NUMBER: _builtins.int
    HASWARNINGS_FIELD_NUMBER: _builtins.int
    HASNOERRORS_FIELD_NUMBER: _builtins.int
    PUBLISHED_FIELD_NUMBER: _builtins.int
    BLINDED_FIELD_NUMBER: _builtins.int
    runId: _builtins.str
    reviewerId: _builtins.str
    reviewDate: _builtins.str
    noErrors: _builtins.bool
    missingOutput: _builtins.bool
    extraneousOutput: _builtins.bool
    invalidOutput: _builtins.bool
    hasErrorOutput: _builtins.bool
    otherErrors: _builtins.bool
    comment: _builtins.str
    hasErrors: _builtins.bool
    hasWarnings: _builtins.bool
    hasNoErrors: _builtins.bool
    published: _builtins.bool
    blinded: _builtins.bool
    def __init__(
        self,
        *,
        runId: _builtins.str | None = ...,
        reviewerId: _builtins.str | None = ...,
        reviewDate: _builtins.str | None = ...,
        noErrors: _builtins.bool | None = ...,
        missingOutput: _builtins.bool | None = ...,
        extraneousOutput: _builtins.bool | None = ...,
        invalidOutput: _builtins.bool | None = ...,
        hasErrorOutput: _builtins.bool | None = ...,
        otherErrors: _builtins.bool | None = ...,
        comment: _builtins.str | None = ...,
        hasErrors: _builtins.bool | None = ...,
        hasWarnings: _builtins.bool | None = ...,
        hasNoErrors: _builtins.bool | None = ...,
        published: _builtins.bool | None = ...,
        blinded: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["blinded", b"blinded", "comment", b"comment", "extraneousOutput", b"extraneousOutput", "hasErrorOutput", b"hasErrorOutput", "hasErrors", b"hasErrors", "hasNoErrors", b"hasNoErrors", "hasWarnings", b"hasWarnings", "invalidOutput", b"invalidOutput", "missingOutput", b"missingOutput", "noErrors", b"noErrors", "otherErrors", b"otherErrors", "published", b"published", "reviewDate", b"reviewDate", "reviewerId", b"reviewerId", "runId", b"runId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blinded", b"blinded", "comment", b"comment", "extraneousOutput", b"extraneousOutput", "hasErrorOutput", b"hasErrorOutput", "hasErrors", b"hasErrors", "hasNoErrors", b"hasNoErrors", "hasWarnings", b"hasWarnings", "invalidOutput", b"invalidOutput", "missingOutput", b"missingOutput", "noErrors", b"noErrors", "otherErrors", b"otherErrors", "published", b"published", "reviewDate", b"reviewDate", "reviewerId", b"reviewerId", "runId", b"runId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RunReview: _TypeAlias = RunReview  # noqa: Y015

@_typing.final
class TaskUser(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Execution(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TRAININGDATASETS_FIELD_NUMBER: _builtins.int
        TESTDATASETS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def trainingDatasets(self) -> _containers.RepeatedCompositeFieldContainer[Global___Dataset]: ...
        @_builtins.property
        def testDatasets(self) -> _containers.RepeatedCompositeFieldContainer[Global___Dataset]: ...
        def __init__(
            self,
            *,
            trainingDatasets: _abc.Iterable[Global___Dataset] | None = ...,
            testDatasets: _abc.Iterable[Global___Dataset] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["testDatasets", b"testDatasets", "trainingDatasets", b"trainingDatasets"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TASK_FIELD_NUMBER: _builtins.int
    USER_FIELD_NUMBER: _builtins.int
    HASVM_FIELD_NUMBER: _builtins.int
    VMINFO_FIELD_NUMBER: _builtins.int
    TASKVMINFO_FIELD_NUMBER: _builtins.int
    SOFTWARES_FIELD_NUMBER: _builtins.int
    SOFTWARESNOTDELETED_FIELD_NUMBER: _builtins.int
    HASSOFTWARESNOTDELETED_FIELD_NUMBER: _builtins.int
    EXECUTION_FIELD_NUMBER: _builtins.int
    RUNS_FIELD_NUMBER: _builtins.int
    RUNSNOTDELETED_FIELD_NUMBER: _builtins.int
    HASRUNSNOTDELETED_FIELD_NUMBER: _builtins.int
    RUNSNOTDELETEDNOTTEST_FIELD_NUMBER: _builtins.int
    EVALUATORRUNSNOTDELETED_FIELD_NUMBER: _builtins.int
    HASEVALUATORRUNSNOTDELETED_FIELD_NUMBER: _builtins.int
    SOFTWARERUNSNOTDELETED_FIELD_NUMBER: _builtins.int
    HASSOFTWARERUNSNOTDELETED_FIELD_NUMBER: _builtins.int
    hasVm: _builtins.bool
    hasSoftwaresNotDeleted: _builtins.bool
    hasRunsNotDeleted: _builtins.bool
    hasEvaluatorRunsNotDeleted: _builtins.bool
    hasSoftwareRunsNotDeleted: _builtins.bool
    @_builtins.property
    def task(self) -> Global___Tasks.Task: ...
    @_builtins.property
    def user(self) -> Global___User: ...
    @_builtins.property
    def vmInfo(self) -> Global___VirtualMachineState: ...
    @_builtins.property
    def taskVmInfo(self) -> Global___VirtualMachineState2: ...
    @_builtins.property
    def softwares(self) -> _containers.RepeatedCompositeFieldContainer[Global___Softwares.Software]: ...
    @_builtins.property
    def softwaresNotDeleted(self) -> _containers.RepeatedCompositeFieldContainer[Global___Softwares.Software]: ...
    @_builtins.property
    def execution(self) -> Global___TaskUser.Execution: ...
    @_builtins.property
    def runs(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExtendedRun]: ...
    @_builtins.property
    def runsNotDeleted(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExtendedRun]: ...
    @_builtins.property
    def runsNotDeletedNotTest(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExtendedRun]: ...
    @_builtins.property
    def evaluatorRunsNotDeleted(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExtendedRun]: ...
    @_builtins.property
    def softwareRunsNotDeleted(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExtendedRun]: ...
    def __init__(
        self,
        *,
        task: Global___Tasks.Task | None = ...,
        user: Global___User | None = ...,
        hasVm: _builtins.bool | None = ...,
        vmInfo: Global___VirtualMachineState | None = ...,
        taskVmInfo: Global___VirtualMachineState2 | None = ...,
        softwares: _abc.Iterable[Global___Softwares.Software] | None = ...,
        softwaresNotDeleted: _abc.Iterable[Global___Softwares.Software] | None = ...,
        hasSoftwaresNotDeleted: _builtins.bool | None = ...,
        execution: Global___TaskUser.Execution | None = ...,
        runs: _abc.Iterable[Global___ExtendedRun] | None = ...,
        runsNotDeleted: _abc.Iterable[Global___ExtendedRun] | None = ...,
        hasRunsNotDeleted: _builtins.bool | None = ...,
        runsNotDeletedNotTest: _abc.Iterable[Global___ExtendedRun] | None = ...,
        evaluatorRunsNotDeleted: _abc.Iterable[Global___ExtendedRun] | None = ...,
        hasEvaluatorRunsNotDeleted: _builtins.bool | None = ...,
        softwareRunsNotDeleted: _abc.Iterable[Global___ExtendedRun] | None = ...,
        hasSoftwareRunsNotDeleted: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["execution", b"execution", "hasEvaluatorRunsNotDeleted", b"hasEvaluatorRunsNotDeleted", "hasRunsNotDeleted", b"hasRunsNotDeleted", "hasSoftwareRunsNotDeleted", b"hasSoftwareRunsNotDeleted", "hasSoftwaresNotDeleted", b"hasSoftwaresNotDeleted", "hasVm", b"hasVm", "task", b"task", "taskVmInfo", b"taskVmInfo", "user", b"user", "vmInfo", b"vmInfo"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["evaluatorRunsNotDeleted", b"evaluatorRunsNotDeleted", "execution", b"execution", "hasEvaluatorRunsNotDeleted", b"hasEvaluatorRunsNotDeleted", "hasRunsNotDeleted", b"hasRunsNotDeleted", "hasSoftwareRunsNotDeleted", b"hasSoftwareRunsNotDeleted", "hasSoftwaresNotDeleted", b"hasSoftwaresNotDeleted", "hasVm", b"hasVm", "runs", b"runs", "runsNotDeleted", b"runsNotDeleted", "runsNotDeletedNotTest", b"runsNotDeletedNotTest", "softwareRunsNotDeleted", b"softwareRunsNotDeleted", "softwares", b"softwares", "softwaresNotDeleted", b"softwaresNotDeleted", "task", b"task", "taskVmInfo", b"taskVmInfo", "user", b"user", "vmInfo", b"vmInfo"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TaskUser: _TypeAlias = TaskUser  # noqa: Y015

@_typing.final
class DatasetRuns(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATASET_FIELD_NUMBER: _builtins.int
    DATASETDEPRECATED_FIELD_NUMBER: _builtins.int
    RUNS_FIELD_NUMBER: _builtins.int
    dataset: _builtins.str
    datasetDeprecated: _builtins.bool
    @_builtins.property
    def runs(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExtendedRun]: ...
    def __init__(
        self,
        *,
        dataset: _builtins.str | None = ...,
        datasetDeprecated: _builtins.bool | None = ...,
        runs: _abc.Iterable[Global___ExtendedRun] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dataset", b"dataset", "datasetDeprecated", b"datasetDeprecated"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dataset", b"dataset", "datasetDeprecated", b"datasetDeprecated", "runs", b"runs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DatasetRuns: _TypeAlias = DatasetRuns  # noqa: Y015

@_typing.final
class TaskDataset(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class DatasetListItem(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        DATASET_FIELD_NUMBER: _builtins.int
        RUNSCOUNT_FIELD_NUMBER: _builtins.int
        ACTIVE_FIELD_NUMBER: _builtins.int
        runsCount: _builtins.int
        active: _builtins.bool
        @_builtins.property
        def dataset(self) -> Global___Dataset: ...
        def __init__(
            self,
            *,
            dataset: Global___Dataset | None = ...,
            runsCount: _builtins.int | None = ...,
            active: _builtins.bool | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "dataset", b"dataset", "runsCount", b"runsCount"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "dataset", b"dataset", "runsCount", b"runsCount"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    DATASETS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def datasets(self) -> _containers.RepeatedCompositeFieldContainer[Global___TaskDataset.DatasetListItem]: ...
    def __init__(
        self,
        *,
        datasets: _abc.Iterable[Global___TaskDataset.DatasetListItem] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["datasets", b"datasets"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TaskDataset: _TypeAlias = TaskDataset  # noqa: Y015

@_typing.final
class TaskReview(_message.Message):
    """TODO: Name deprecated."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SoftwareRunning(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPE_FIELD_NUMBER: _builtins.int
        RUNID_FIELD_NUMBER: _builtins.int
        TIME_FIELD_NUMBER: _builtins.int
        type: _builtins.str
        runId: _builtins.str
        time: _builtins.str
        def __init__(
            self,
            *,
            type: _builtins.str | None = ...,
            runId: _builtins.str | None = ...,
            time: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["runId", b"runId", "time", b"time", "type", b"type"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["runId", b"runId", "time", b"time", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class TaskUser(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USER_FIELD_NUMBER: _builtins.int
        USERSIGNEDIN_FIELD_NUMBER: _builtins.int
        SOFTWARES_FIELD_NUMBER: _builtins.int
        SOFTWARESDELETED_FIELD_NUMBER: _builtins.int
        SOFTWARERUNNING_FIELD_NUMBER: _builtins.int
        RUNNINGSOFTWARE_FIELD_NUMBER: _builtins.int
        RUNSTOTAL_FIELD_NUMBER: _builtins.int
        RUNSREVIEWED_FIELD_NUMBER: _builtins.int
        RUNSUNREVIEWED_FIELD_NUMBER: _builtins.int
        userSignedIn: _builtins.bool
        softwares: _builtins.int
        softwaresDeleted: _builtins.int
        softwareRunning: _builtins.bool
        runsTotal: _builtins.int
        runsReviewed: _builtins.int
        runsUnreviewed: _builtins.int
        @_builtins.property
        def user(self) -> Global___User: ...
        @_builtins.property
        def runningSoftware(self) -> Global___TaskReview.SoftwareRunning: ...
        def __init__(
            self,
            *,
            user: Global___User | None = ...,
            userSignedIn: _builtins.bool | None = ...,
            softwares: _builtins.int | None = ...,
            softwaresDeleted: _builtins.int | None = ...,
            softwareRunning: _builtins.bool | None = ...,
            runningSoftware: Global___TaskReview.SoftwareRunning | None = ...,
            runsTotal: _builtins.int | None = ...,
            runsReviewed: _builtins.int | None = ...,
            runsUnreviewed: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["runningSoftware", b"runningSoftware", "runsReviewed", b"runsReviewed", "runsTotal", b"runsTotal", "runsUnreviewed", b"runsUnreviewed", "softwareRunning", b"softwareRunning", "softwares", b"softwares", "softwaresDeleted", b"softwaresDeleted", "user", b"user", "userSignedIn", b"userSignedIn"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["runningSoftware", b"runningSoftware", "runsReviewed", b"runsReviewed", "runsTotal", b"runsTotal", "runsUnreviewed", b"runsUnreviewed", "softwareRunning", b"softwareRunning", "softwares", b"softwares", "softwaresDeleted", b"softwaresDeleted", "user", b"user", "userSignedIn", b"userSignedIn"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TASKUSERS_FIELD_NUMBER: _builtins.int
    TASK_FIELD_NUMBER: _builtins.int
    HASRUNS_FIELD_NUMBER: _builtins.int
    RUNS_FIELD_NUMBER: _builtins.int
    HASEVALUATORRUNS_FIELD_NUMBER: _builtins.int
    EVALUATORRUNS_FIELD_NUMBER: _builtins.int
    hasRuns: _builtins.bool
    hasEvaluatorRuns: _builtins.bool
    @_builtins.property
    def taskUsers(self) -> _containers.RepeatedCompositeFieldContainer[Global___TaskReview.TaskUser]: ...
    @_builtins.property
    def task(self) -> Global___Tasks.Task: ...
    @_builtins.property
    def runs(self) -> _containers.RepeatedCompositeFieldContainer[Global___DatasetRuns]: ...
    @_builtins.property
    def evaluatorRuns(self) -> _containers.RepeatedCompositeFieldContainer[Global___DatasetRuns]: ...
    def __init__(
        self,
        *,
        taskUsers: _abc.Iterable[Global___TaskReview.TaskUser] | None = ...,
        task: Global___Tasks.Task | None = ...,
        hasRuns: _builtins.bool | None = ...,
        runs: _abc.Iterable[Global___DatasetRuns] | None = ...,
        hasEvaluatorRuns: _builtins.bool | None = ...,
        evaluatorRuns: _abc.Iterable[Global___DatasetRuns] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["hasEvaluatorRuns", b"hasEvaluatorRuns", "hasRuns", b"hasRuns", "task", b"task"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["evaluatorRuns", b"evaluatorRuns", "hasEvaluatorRuns", b"hasEvaluatorRuns", "hasRuns", b"hasRuns", "runs", b"runs", "task", b"task", "taskUsers", b"taskUsers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TaskReview: _TypeAlias = TaskReview  # noqa: Y015

@_typing.final
class TaskReviewUser(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_FIELD_NUMBER: _builtins.int
    TASK_FIELD_NUMBER: _builtins.int
    USERDATASETRUNS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def user(self) -> Global___User: ...
    @_builtins.property
    def task(self) -> Global___Tasks.Task: ...
    @_builtins.property
    def userDatasetRuns(self) -> _containers.RepeatedCompositeFieldContainer[Global___DatasetRuns]: ...
    def __init__(
        self,
        *,
        user: Global___User | None = ...,
        task: Global___Tasks.Task | None = ...,
        userDatasetRuns: _abc.Iterable[Global___DatasetRuns] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["task", b"task", "user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["task", b"task", "user", b"user", "userDatasetRuns", b"userDatasetRuns"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TaskReviewUser: _TypeAlias = TaskReviewUser  # noqa: Y015

@_typing.final
class TaskReviewUserRun(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_FIELD_NUMBER: _builtins.int
    TASK_FIELD_NUMBER: _builtins.int
    RUN_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def user(self) -> Global___User: ...
    @_builtins.property
    def task(self) -> Global___Tasks.Task: ...
    @_builtins.property
    def run(self) -> Global___ExtendedRun: ...
    def __init__(
        self,
        *,
        user: Global___User | None = ...,
        task: Global___Tasks.Task | None = ...,
        run: Global___ExtendedRun | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["run", b"run", "task", b"task", "user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run", b"run", "task", b"task", "user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TaskReviewUserRun: _TypeAlias = TaskReviewUserRun  # noqa: Y015

@_typing.final
class Error(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    URL_FIELD_NUMBER: _builtins.int
    STATUSCODE_FIELD_NUMBER: _builtins.int
    IS401_FIELD_NUMBER: _builtins.int
    IS404_FIELD_NUMBER: _builtins.int
    ISDIRECT_FIELD_NUMBER: _builtins.int
    ERRORMESSAGE_FIELD_NUMBER: _builtins.int
    STACKTRACE_FIELD_NUMBER: _builtins.int
    CAUSES_FIELD_NUMBER: _builtins.int
    HASCAUSES_FIELD_NUMBER: _builtins.int
    url: _builtins.str
    statusCode: _builtins.int
    is401: _builtins.bool
    is404: _builtins.bool
    isDirect: _builtins.bool
    errorMessage: _builtins.str
    stackTrace: _builtins.str
    hasCauses: _builtins.bool
    @_builtins.property
    def causes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        url: _builtins.str | None = ...,
        statusCode: _builtins.int | None = ...,
        is401: _builtins.bool | None = ...,
        is404: _builtins.bool | None = ...,
        isDirect: _builtins.bool | None = ...,
        errorMessage: _builtins.str | None = ...,
        stackTrace: _builtins.str | None = ...,
        causes: _abc.Iterable[_builtins.str] | None = ...,
        hasCauses: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["errorMessage", b"errorMessage", "hasCauses", b"hasCauses", "is401", b"is401", "is404", b"is404", "isDirect", b"isDirect", "stackTrace", b"stackTrace", "statusCode", b"statusCode", "url", b"url"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["causes", b"causes", "errorMessage", b"errorMessage", "hasCauses", b"hasCauses", "is401", b"is401", "is404", b"is404", "isDirect", b"isDirect", "stackTrace", b"stackTrace", "statusCode", b"statusCode", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Error: _TypeAlias = Error  # noqa: Y015
