#docker build -t webis/tira:python-client-dev-0.0.5 -f Dockerfile.dev .
FROM ubuntu:latest

ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
	&& apt-get install -y python3 python3-pip build-essential openjdk-11-jdk \
	&& apt-get install -y sudo git locales

RUN echo "en_US.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen && locale-gen

RUN apt-get install -y curl \
	&& curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
	&& chmod a+r /etc/apt/keyrings/docker.gpg \
	&& echo \
		"deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
		"$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
		tee /etc/apt/sources.list.d/docker.list > /dev/null \
	&& apt-get update -y \
	&& apt-get install -y docker-ce-cli

# Change root Password to 1234
RUN echo 'root:1234' | chpasswd

RUN pip3 install twine coverage-badge python-terrier coverage
RUN pip3 install pytest docker
RUN pip3 install sphinx furo myst-parser sphinx-design sphinxcontrib-plantuml sphinxcontrib-umlet
RUN apt-get update && apt-get install -y plantuml
RUN pip3 install tira approvaltests \
	&& cd /tmp \
	&& python3 -c 'from tira.third_party_integrations import ensure_pyterrier_is_loaded; ensure_pyterrier_is_loaded();' \
	&& pip3 uninstall -y tira

# Create new user: "dev" with password "1234" and change to that user
RUN useradd -ms /bin/bash dev \
 	&& echo 'dev:1234' | chpasswd \
	&& usermod -aG sudo dev \
	&& groupadd -g 973 docker \
	&& usermod -aG docker dev
USER dev

