#docker build -t webis/tira:python-client-dev-0.0.5-python3.7 -f Dockerfile.dev-python3.7 .
FROM mam10eks/splade_tira:0.0.1

RUN apt-get install -y curl gpg \
	&& mkdir /etc/apt/keyrings/ \
	&& curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
	&& chmod a+r /etc/apt/keyrings/docker.gpg \
	&& echo \
		"deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
		"$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
		tee /etc/apt/sources.list.d/docker.list > /dev/null \
	&& apt-get update -y \
	&& apt-get install -y docker-ce-cli

RUN pip3 install twine coverage-badge python-terrier coverage approvaltests
RUN pip3 install pytest docker
