#docker build -t webis/tira:python-client-dev-0.0.1 -f Dockerfile.dev .
FROM ubuntu:latest

RUN apt-get update \
	&& apt-get install -y python3 python3-pip build-essential openjdk-11-jdk

RUN pip3 install twine coverage-badge python-terrier coverage

RUN pip3 install pytest docker

