# docker build -t webis/tira:vuetify-dev-0.0.1 -f Dockerfile.dev .
FROM node

ADD package.json yarn.lock vite.config.ts jest.config.js babel.config.js /tmp-del/

RUN cd /tmp-del \
	&& yarn create vuetify \
	&& yarn install \
	&& yarn install --dev \
	&& mv node_modules/* /usr/local/lib/node_modules \
	&& mv node_modules/.bin /usr/local/lib/node_modules/.bin \
	&& mv node_modules/.yarn-integrity /usr/local/lib/node_modules/.yarn-integrity \
	&& cd / \
	&& rm -R /tmp-del/

