# Generated by Django 5.0.9 on 2024-12-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0003_dataset_chatnoir_id_dataset_ir_datasets_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MirroredResource",
            fields=[
                ("md5_sum", models.CharField(max_length=150, primary_key=True, serialize=False)),
                ("md5_first_kilobyte", models.CharField(max_length=150)),
                ("size", models.BigIntegerField()),
                ("mirrors", models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DatasetHasMirroredResource",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tira.dataset")),
                (
                    "mirrored_resource",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tira.mirroredresource"),
                ),
            ],
        ),
    ]
