# Generated by Django 5.0.9 on 2024-12-02 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0006_dataset_ir_datasets_id_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousUploads",
            fields=[
                ("uuid", models.CharField(max_length=150, primary_key=True, serialize=False)),
                ("created", models.DateField(auto_now_add=True)),
                ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tira.dataset")),
            ],
        ),
    ]
