# Generated by Django 5.0.9 on 2025-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0008_dataset_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="mirroredresource",
            name="subdirectory",
            field=models.TextField(default=None, null=True),
        ),
    ]
