# Generated by Django 5.0.9 on 2025-01-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0009_mirroredresource_subdirectory"),
    ]

    operations = [
        migrations.AddField(
            model_name="mirroredresource",
            name="rename_to",
            field=models.TextField(default=None, null=True),
        ),
    ]
