# Generated by Django 5.0.9 on 2025-01-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0010_mirroredresource_rename_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mirroredresource",
            name="rename_to",
        ),
        migrations.RemoveField(
            model_name="mirroredresource",
            name="subdirectory",
        ),
        migrations.AddField(
            model_name="datasethasmirroredresource",
            name="rename_to",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="datasethasmirroredresource",
            name="subdirectory",
            field=models.TextField(default=None, null=True),
        ),
    ]
