# Generated by Django 5.0.9 on 2025-01-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0013_alter_dataset_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousuploads",
            name="has_metadata",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="anonymousuploads",
            name="metadata_git_repo",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="anonymousuploads",
            name="metadata_has_notebook",
            field=models.BooleanField(default=False),
        ),
    ]
