# Generated by Django 5.0.9 on 2025-03-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0014_anonymousuploads_has_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockersoftware",
            name="active_branch",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="dockersoftware",
            name="commit",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="dockersoftware",
            name="source_code_remotes",
            field=models.TextField(default=None, null=True),
        ),
    ]
