# Generated by Django 5.0.9 on 2025-03-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0016_rename_active_branch_dockersoftware_source_code_active_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousuploads",
            name="valid_formats",
            field=models.TextField(default=None, null=True),
        ),
    ]
