# Generated by Django 5.0.9 on 2025-04-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0021_alter_dataset_format_configuration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="valid_formats",
            field=models.TextField(default=None, null=True),
        ),
    ]
