# Generated by Django 5.0.9 on 2025-05-18 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0022_run_valid_formats"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="from_upload",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to="tira.anonymousuploads"
            ),
        ),
    ]
