# Generated by Django 5.0.9 on 2025-09-15 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0023_run_from_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousuploads",
            name="mirrored_resource",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to="tira.mirroredresource"
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="mirrored_resource",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to="tira.mirroredresource"
            ),
        ),
    ]
