# Generated by Django 5.0.9 on 2025-09-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0024_anonymousuploads_mirrored_resource_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="vm",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="tira.virtualmachine"
            ),
        ),
    ]
