# Generated by Django 5.0.9 on 2025-12-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0026_task_aggregated_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunningProcesses",
            fields=[
                ("uuid", models.CharField(max_length=150, primary_key=True, serialize=False)),
                ("dataset", models.TextField(default="")),
                ("task", models.TextField(default="")),
                ("vm_id", models.TextField(default="")),
            ],
        ),
    ]
