# Generated by Django 5.0.9 on 2026-02-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0029_runningprocesses_dataset_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="submission_tabs",
            field=models.TextField(default=None, null=True),
        ),
    ]
