# Generated by Django 5.0.9 on 2026-03-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0031_dataset_workflow_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockersoftware",
            name="workflow_configuration",
            field=models.TextField(default=None, null=True),
        ),
    ]
