# Generated by Django 5.0.9 on 2026-04-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0032_dockersoftware_workflow_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="runningprocesses",
            name="killing",
            field=models.BooleanField(default=False),
        ),
    ]
