# Generated by Django 5.0.9 on 2026-05-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0034_dataset_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="runningprocesses",
            name="celery_id",
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
