# Generated by Django 5.0.9 on 2026-06-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0035_runningprocesses_celery_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockersoftware",
            name="forward_environment_variable",
            field=models.TextField(default=None, null=True),
        ),
    ]
