# Generated by Django 5.0.9 on 2026-06-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0037_dataset_is_visible_to_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockersoftware",
            name="cache_behaviour",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
