# Generated by Django 5.0.9 on 2026-06-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0038_dockersoftware_cache_behaviour"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockersoftware",
            name="mount_config",
            field=models.TextField(default=None, null=True),
        ),
    ]
