# Generated by Django 5.0.9 on 2026-06-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tira", "0039_dockersoftware_mount_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockersoftware",
            name="cache_behaviour",
            field=models.CharField(
                choices=[("deterministic", "deterministic"), ("not-deterministic", "not-deterministic")],
                default=None,
                max_length=17,
                null=True,
            ),
        ),
    ]
