# Generated by Django 5.0.9 on 2026-07-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0040_alter_dockersoftware_cache_behaviour_enum"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="upload_form_fields",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="upload_metadata",
            field=models.TextField(default=None, null=True),
        ),
    ]
