# Generated by Django 5.0.9 on 2026-10-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tira", "0049_task_task_export_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockersoftware",
            name="metadata",
            field=models.TextField(default=None, null=True),
        ),
    ]
