java:
	python -m grpc_tools.protoc -I=. --python_out=python_out --grpc_python_out=python_out ./src/TiraHostMessages.proto

python:
	python -m grpc_tools.protoc -I=. --python_out=python_out --grpc_python_out=python_out ./src/TiraHostMessages.proto
