# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import tira_messages_pb2 as tira__messages__pb2
import tira_to_web_pb2 as tira__to__web__pb2


class TiraProtocolStub(object):
    """-----------------------------------------------------------------------------
    Message definitions
    -----------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDataset = channel.unary_unary(
            "/tira.TiraProtocol/GetDataset",
            request_serializer=tira__to__web__pb2.DatasetRequest.SerializeToString,
            response_deserializer=tira__messages__pb2.Dataset.FromString,
        )


class TiraProtocolServicer(object):
    """-----------------------------------------------------------------------------
    Message definitions
    -----------------------------------------------------------------------------

    """

    def GetDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TiraProtocolServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetDataset": grpc.unary_unary_rpc_method_handler(
            servicer.GetDataset,
            request_deserializer=tira__to__web__pb2.DatasetRequest.FromString,
            response_serializer=tira__messages__pb2.Dataset.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("tira.TiraProtocol", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class TiraProtocol(object):
    """-----------------------------------------------------------------------------
    Message definitions
    -----------------------------------------------------------------------------

    """

    @staticmethod
    def GetDataset(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tira.TiraProtocol/GetDataset",
            tira__to__web__pb2.DatasetRequest.SerializeToString,
            tira__messages__pb2.Dataset.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
