# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tira_to_web.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tira_messages_pb2 as tira__messages__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='tira_to_web.proto',
  package='tira',
  syntax='proto3',
  serialized_options=b'\n\035de.webis.tira.client.web.grpcH\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11tira_to_web.proto\x12\x04tira\x1a\x13tira_messages.proto\"3\n\x0e\x44\x61tasetRequest\x12\x11\n\tdatasetID\x18\x01 \x01(\t\x12\x0e\n\x06taskID\x18\x02 \x01(\t2A\n\x0cTiraProtocol\x12\x31\n\nGetDataset\x12\x14.tira.DatasetRequest\x1a\r.tira.DatasetB!\n\x1d\x64\x65.webis.tira.client.web.grpcH\x01\x62\x06proto3'
  ,
  dependencies=[tira__messages__pb2.DESCRIPTOR,])




_DATASETREQUEST = _descriptor.Descriptor(
  name='DatasetRequest',
  full_name='tira.DatasetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='datasetID', full_name='tira.DatasetRequest.datasetID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taskID', full_name='tira.DatasetRequest.taskID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['DatasetRequest'] = _DATASETREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DatasetRequest = _reflection.GeneratedProtocolMessageType('DatasetRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATASETREQUEST,
  '__module__' : 'tira_to_web_pb2'
  # @@protoc_insertion_point(class_scope:tira.DatasetRequest)
  })
_sym_db.RegisterMessage(DatasetRequest)


DESCRIPTOR._options = None

_TIRAPROTOCOL = _descriptor.ServiceDescriptor(
  name='TiraProtocol',
  full_name='tira.TiraProtocol',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=101,
  serialized_end=166,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDataset',
    full_name='tira.TiraProtocol.GetDataset',
    index=0,
    containing_service=None,
    input_type=_DATASETREQUEST,
    output_type=tira__messages__pb2._DATASET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TIRAPROTOCOL)

DESCRIPTOR.services_by_name['TiraProtocol'] = _TIRAPROTOCOL

# @@protoc_insertion_point(module_scope)
