# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TiraHostMessages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TiraClientWebMessages_pb2 as TiraClientWebMessages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TiraHostMessages.proto',
  package='tira.generated',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16TiraHostMessages.proto\x12\x0etira.generated\x1a\x1bTiraClientWebMessages.proto\"\x15\n\x05Input\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x16\n\x06Output\x12\x0c\n\x04text\x18\x01 \x01(\t\"5\n\x07Request\x12*\n\x02vm\x18\x01 \x01(\x0b\x32\x1e.tira.generated.VirtualMachine\"=\n\x05Reply\x12\x34\n\x07vmstate\x18\x01 \x01(\x0b\x32#.tira.generated.VirtualMachineState2\xc6\x01\n\x0fTiraHostService\x12>\n\nget_status\x12\x17.tira.generated.Request\x1a\x15.tira.generated.Reply\"\x00\x12:\n\x06\x62\x61\x63kup\x12\x17.tira.generated.Request\x1a\x15.tira.generated.Reply\"\x00\x12\x37\n\x04test\x12\x15.tira.generated.Input\x1a\x16.tira.generated.Output\"\x00\x62\x06proto3'
  ,
  dependencies=[TiraClientWebMessages__pb2.DESCRIPTOR,])




_INPUT = _descriptor.Descriptor(
  name='Input',
  full_name='tira.generated.Input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='tira.generated.Input.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=92,
)


_OUTPUT = _descriptor.Descriptor(
  name='Output',
  full_name='tira.generated.Output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='tira.generated.Output.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=116,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='tira.generated.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vm', full_name='tira.generated.Request.vm', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=171,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='tira.generated.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vmstate', full_name='tira.generated.Reply.vmstate', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=234,
)

_REQUEST.fields_by_name['vm'].message_type = TiraClientWebMessages__pb2._VIRTUALMACHINE
_REPLY.fields_by_name['vmstate'].message_type = TiraClientWebMessages__pb2._VIRTUALMACHINESTATE
DESCRIPTOR.message_types_by_name['Input'] = _INPUT
DESCRIPTOR.message_types_by_name['Output'] = _OUTPUT
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'TiraHostMessages_pb2'
  # @@protoc_insertion_point(class_scope:tira.generated.Input)
  })
_sym_db.RegisterMessage(Input)

Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUT,
  '__module__' : 'TiraHostMessages_pb2'
  # @@protoc_insertion_point(class_scope:tira.generated.Output)
  })
_sym_db.RegisterMessage(Output)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'TiraHostMessages_pb2'
  # @@protoc_insertion_point(class_scope:tira.generated.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'TiraHostMessages_pb2'
  # @@protoc_insertion_point(class_scope:tira.generated.Reply)
  })
_sym_db.RegisterMessage(Reply)



_TIRAHOSTSERVICE = _descriptor.ServiceDescriptor(
  name='TiraHostService',
  full_name='tira.generated.TiraHostService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=237,
  serialized_end=435,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_status',
    full_name='tira.generated.TiraHostService.get_status',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='backup',
    full_name='tira.generated.TiraHostService.backup',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='test',
    full_name='tira.generated.TiraHostService.test',
    index=2,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TIRAHOSTSERVICE)

DESCRIPTOR.services_by_name['TiraHostService'] = _TIRAHOSTSERVICE

# @@protoc_insertion_point(module_scope)
