# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import TiraHostMessages_pb2 as TiraHostMessages__pb2


class TiraHostServiceStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_status = channel.unary_unary(
                '/tira.generated.TiraHostService/get_status',
                request_serializer=TiraHostMessages__pb2.Request.SerializeToString,
                response_deserializer=TiraHostMessages__pb2.Reply.FromString,
                )
        self.backup = channel.unary_unary(
                '/tira.generated.TiraHostService/backup',
                request_serializer=TiraHostMessages__pb2.Request.SerializeToString,
                response_deserializer=TiraHostMessages__pb2.Reply.FromString,
                )
        self.test = channel.unary_unary(
                '/tira.generated.TiraHostService/test',
                request_serializer=TiraHostMessages__pb2.Input.SerializeToString,
                response_deserializer=TiraHostMessages__pb2.Output.FromString,
                )


class TiraHostServiceServicer(object):
    """The service definition.
    """

    def get_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def backup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def test(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TiraHostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_status,
                    request_deserializer=TiraHostMessages__pb2.Request.FromString,
                    response_serializer=TiraHostMessages__pb2.Reply.SerializeToString,
            ),
            'backup': grpc.unary_unary_rpc_method_handler(
                    servicer.backup,
                    request_deserializer=TiraHostMessages__pb2.Request.FromString,
                    response_serializer=TiraHostMessages__pb2.Reply.SerializeToString,
            ),
            'test': grpc.unary_unary_rpc_method_handler(
                    servicer.test,
                    request_deserializer=TiraHostMessages__pb2.Input.FromString,
                    response_serializer=TiraHostMessages__pb2.Output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tira.generated.TiraHostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TiraHostService(object):
    """The service definition.
    """

    @staticmethod
    def get_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tira.generated.TiraHostService/get_status',
            TiraHostMessages__pb2.Request.SerializeToString,
            TiraHostMessages__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def backup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tira.generated.TiraHostService/backup',
            TiraHostMessages__pb2.Request.SerializeToString,
            TiraHostMessages__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tira.generated.TiraHostService/test',
            TiraHostMessages__pb2.Input.SerializeToString,
            TiraHostMessages__pb2.Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
