FROM ubuntu:24.04

ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y sudo git locales
RUN echo "en_US.UTF-8 UTF-8" | tee -a /etc/locale.gen && locale-gen

########################################################################################################################
# Create User                                                                                                          #
########################################################################################################################
# Change root Password to 1234
RUN echo 'root:1234' | chpasswd
# Create new user: "dev" also with password 1234
RUN useradd -ms /bin/bash dev && \
    echo 'dev:1234' | chpasswd && \
    usermod -aG sudo dev


########################################################################################################################
# Frontend                                                                                                             #
########################################################################################################################
USER root

RUN <<EOF
    apt-get update
    apt-get install -y npm
    npm install --global yarn
EOF




########################################################################################################################
# Backend (Application)                                                                                                #
########################################################################################################################
ENV PIP_BREAK_SYSTEM_PACKAGES 1
USER root
RUN apt-get update && apt-get install -y python3 python3-pip python3-dev pkg-config default-libmysqlclient-dev \
    libpcre3-dev
# Create a dummy secret
COPY <<EOF /etc/discourse/client-api-key
I am so secret
EOF

########################################################################################################################
# Client                                                                                                               #
########################################################################################################################
USER root
RUN <<EOF
    apt-get update
    apt-get install -y openjdk-11-jdk
EOF



########################################################################################################################
# Documentation                                                                                                        #
########################################################################################################################
ENV PIP_BREAK_SYSTEM_PACKAGES 1
USER root
RUN apt-get update && apt-get install -y python3 python3-pip pkg-config plantuml wget
# Install umlet
RUN mkdir -p /usr/share/umlet \
	&& cd /usr/share/umlet \
	&& wget https://www.umlet.com/download/umlet_15_1/umlet-standalone-15.1.zip -O download.zip \
	&& cd /usr/share/umlet \
	&& unzip download.zip
USER dev
RUN pip3 install sphinx furo myst-parser sphinx-toolbox sphinx-design sphinxcontrib-plantuml sphinxcontrib-umlet
