#!/bin/bash

for D in /resource/*; do
    BASED_D=$(basename $D)
    if [ ! -d /shared/$BASED_D ]
    then
        cp -r $D /shared/
    fi
done

# owners
chown -R discourse:www-data /shared/backups
chown -R discourse:www-data /shared/tmp
chown -R discourse:www-data /shared/uploads

chown -R redis:redis /shared/redis_data

chown -R postgres:postgres /shared/postgres_backup
chown -R postgres:postgres /shared/postgres_data
chown -R postgres:postgres /shared/postgres_run

# timeouts
sed -i s/"timeout 30"/"timeout 300"/g /var/www/discourse/config/unicorn.conf.rb
sed -i '/include \/etc\/nginx\/sites-enabled\/\*;/a \\tproxy_send_timeout 300;\n\tproxy_read_timeout 300;' /etc/nginx/nginx.conf

# stop fonts route from getting rerouted
sed -i s/"fonts|"/""/g /etc/nginx/conf.d/discourse.conf
