# For your convenience, we marked secrets with [SECRET]. Make sure, you change these
# values from their defaults!

##########################################################################################
# TIRA                                                                                   #
##########################################################################################
# Enables debug mode. This means more verbose output in the console and for the REST-API.
# Settings this value to true in production is a security risk!
debug: !ENV ${TIRA_DEBUG:false}

tira_root: !ENV ${TIRA_ROOT:/tira}
# The directory where logs are written to. Defaults to TIRA_ROOT/log/tira-application
# logging_dir: /mnt/ceph/tira/log/tira-application

# [SECRET]
github_token: !ENV ${TIRA_GITHUB_TOKEN}

##########################################################################################
# Database                                                                               #
##########################################################################################
database:
  # django.db.backends.mysql or django.db.backends.sqlite3
  engine: !ENV ${TIRA_DB_ENGINE:django.db.backends.sqlite3}
  # when backend is sqlite, this will be the name of the database below TIRA_ROOT/state
  name: !ENV ${TIRA_DB_NAME:tira}
  user: !ENV ${TIRA_DB_USER:tira} # ignored when using sqlite3
  password: !ENV ${TIRA_DB_PASSWORD} # ignored when using sqlite3
  host: !ENV ${TIRA_DB_HOST:tira-mariadb} # ignored when using sqlite3
  port: !ENV ${TIRA_DB_PORT:3306} # ignored when using sqlite3

##########################################################################################
# Discourse                                                                              #
##########################################################################################
discourse_api_url: !ENV ${DISCOURSE_API_URL:https://www.tira.io}

# [SECRET]
discourse_api_key: !ENV ${DISCOURSE_API_KEY:""}

##########################################################################################
# Django                                                                                 #
##########################################################################################
# A list of hostnames using which the backend may be addressed. The value "*" denotes any
# address. A value of ["tira.example.com", "example.com"] would only allow requests made
# addressing these hostnames. See
# https://docs.djangoproject.com/en/5.1/ref/settings/#allowed-hosts for more information.
allowed_hosts:
  - "*"

# [SECRET] See https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-SECRET_KEY
# for more information.
django_secret: !ENV ${DJANGO_SECRET:change-me!}

##########################################################################################
# Deprecated and removed soon (we hope)                                                  #
##########################################################################################
# grpc_host can be local or remote. If local, it will call localhost (i.e., for testing).
# If remote, it will call the vm-host. When developing, set this option to local,
# otherwise you might accidentally remote-control the live-vms.
grpc_host: local
host_grpc_port: 50051
application_grpc_port: 50052

tira_rest_api:
  base_url: !ENV ${TIRA_API_BASE_URL:https://www.tira.io}
  grpc_url: !ENV ${TIRA_GRPC_BASE_URL:https://www.tira.io}
  archived_url: !ENV ${TIRA_ARCHIVED_URL:https://archive.tira.io}
  login_url: !ENV ${TIRA_LOGIN_URL:https://www.tira.io}
  logout_url: !ENV ${TIRA_LOGOUT_URL:https://www.tira.io}
  disraptor_url: !ENV ${TIRA_DISRAPTOR_URL:https://www.tira.io}
  notifications_url: !ENV ${TIRA_NOTIFICATIONS_URL:https://www.tira.io}
