FROM ubuntu:24.04

ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN apt-get -qq update && \
	apt-get -qq install -y python3 python3-pip git

WORKDIR /tira/
COPY ./worker ./
COPY ./python-client ../python-client

RUN pip3 install -q --no-cache-dir ../python-client "./[test]"

RUN TIRA_WORKER_CONFIG=/tira/tira-worker-config.yml PYTHONPATH=/tira/src pytest -q tests

RUN apt-get update && apt-get -qq install sudo tree podman

########################################################################################################################
# Final Configuration Stuff                                                                                            #
########################################################################################################################
ENV PATH=/home/tira/.local/bin:$PATH
# CONFIGURE THE FOLLOWING ENVIRONMENT VARIABLES IN YOUR DOCKER-COMPOSE FILE
ENV TIRA_WORKER_CONFIG=/tira/config/tira-worker-config.yml
ENV TIRA_DEBUG=false

EXPOSE 8080

CMD ["celery", "-A", "tira_worker:app", "worker"]
