name: Upload Software to TIRA
on:
  workflow_dispatch:
    directory:
      description: 'The directory that contains the submission. Can be . for the root of the repository'
      required: true
      default: .
jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install required python packages
        run: |
          python -m pip install --upgrade pip
          pip3 install tira
      - name: Build, test, and upload image
        run: |
          tira-cli login --token {% verbatim %}${{ secrets.TIRA_CLIENT_TOKEN }}{% endverbatim %}
          tira-cli verify-installation
          tira-cli code-submission --path {% verbatim %}${{ inputs.directory }}{% endverbatim %} --task {{ task_id }} --dataset {{ input_dataset }}

