name: Documentation
on:
  push:
    branches:
      - main

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get install -y python3-pip
          pip install sphinx furo myst-parser sphinx-toolbox
          pip install pandas pyterrier ir_datasets
          cd python-client/sphinx
          # sphinx-apidoc -o . ../tira
          make doctest
          make html
          touch _build/html/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: python-client/sphinx/_build/html
          target-folder: ./
          clean-exclude: nightly
