name: Linters

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  pull_request: {}

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        directory: [application, python-client]
    steps:
      - uses: actions/checkout@v4
        continue-on-error: false
      - name: Set up Python 3.9
        continue-on-error: false
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install mypy
        run: pip3 install mypy
      - name: Run mypy on ${{ matrix.directory }}
        working-directory: ${{github.workspace}}/${{ matrix.directory }}
        run: |
          mkdir .mypy_cache
          mypy . --non-interactive --cache-dir=.mypy_cache/

  flake8:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        directory: [application, python-client]
    steps:
      - uses: actions/checkout@v4
        continue-on-error: false
      - name: Set up Python 3.9
        continue-on-error: false
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install flake8
        run: pip3 install flake8
      - name: Run flake8 on ${{ matrix.directory }}
        working-directory: ${{github.workspace}}/${{ matrix.directory }}
        run: flake8 .

  black:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        directory: [application, python-client]
    steps:
      - uses: actions/checkout@v4
        continue-on-error: false
      - name: Set up Python 3.9
        continue-on-error: false
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install black
        run: pip3 install black
      - name: Run black on ${{ matrix.directory }}
        working-directory: ${{github.workspace}}/${{ matrix.directory }}
        run: black --check .

  isort:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        directory: [application, python-client]
    steps:
      - uses: actions/checkout@v4
        continue-on-error: false
      - name: Set up Python 3.9
        continue-on-error: false
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install isort
        run: pip3 install isort
      - name: Run isort on ${{ matrix.directory }}
        working-directory: ${{github.workspace}}/${{ matrix.directory }}
        run: isort --check .
